source("R/01_setup.R")
data <- list(QDS = read_csv(glue("{data_dir}/data-QDS-w-residuals.csv")))
ggplot(data$QDS, aes(PC1, PC1_residual)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(PC1, multivariate_residual)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(PC1, PC1_residual)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(Elevation, PC1_residual)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(Elevation, PC1)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(n_collections, PC1_residual)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(PC1_residual, n_collections)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(PC1_residual, log(n_collections))) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(n_collections, PC1_residual)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(log(n_collections), PC1_residual)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(n_collections, QDS_richness)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(PC1, QDS_richness / n_collections)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(PC1_residual, n_collections / QDS_richness)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(PC1_residual, n_collections)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(PC1_residual, QDS_collection)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(QDS_richness, PC1_residual)) + geom_point(aes(colour = region)) + geom_hline(yintercept = 0)
ggplot(data$QDS, aes(PC1, QDS_richness)) + geom_point(aes(colour = PC1_residual)) + geom_hline(yintercept = 0)
ggplot(data$QDS, aes(PC1, QDS_richness)) + geom_point(aes(colour = PC1_residual)) + scale_colour_viridis_c()
ggplot(data$QDS, aes(PC1, QDS_richness)) + geom_point(aes(colour = PC1_residual)) + scale_colour_viridis_c() + geom_smooth(method = lm)
ggplot(data$QDS, aes(lat, PC1_residual)) + geom_point(aes(colour = region)) + geom_hline(yintercept = 0)
ggplot(data$QDS, aes(lon, PC1_residual)) + geom_point(aes(colour = region)) + geom_hline(yintercept = 0)
ggplot(data$QDS, aes(lat + lon, PC1_residual)) + geom_point(aes(colour = region)) + geom_hline(yintercept = 0)
ggplot(data$QDS, aes(lat^2, PC1_residual)) + geom_point(aes(colour = region)) + geom_hline(yintercept = 0)
ggplot(data$QDS, aes(Elevation, PC1_residual)) + geom_point(aes(colour = region)) + geom_hline(yintercept = 0)
ggplot(data$QDS, aes(Elevation, PC1_residual)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(PC1, PC1_residual)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(PC1, multivariate_residual)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(n_collections, multivariate_residual)) + geom_point(aes(colour = region))
ggplot(data$QDS, aes(n_collections, PC1)) + geom_point(aes(colour = region))
prcomp(data$QDS[, c("lat", "lon")], centre = TRUE, scale. = TRUE)
pca_GCFR <- prcomp(data$QDS[data$QDS$region == "GCFR", c("lat", "lon")], center = TRUE, scale. = TRUE)
pca_SWAFR <- prcomp(data$QDS[data$QDS$region == "SWAFR", c("lat", "lon")], center = TRUE, scale. = TRUE)
autoplot(pca_GCFR)
plot(data$QDS$QDS_richness[data$QDS$region == "GCFR"] ~ pca_GCFR$x[, 1])
plot(data$QDS$PC1[data$QDS$region == "GCFR"] ~ pca_GCFR$x[, 1])
plot(data$QDS$PC1 ~ c(pca_GCFR$x[, 1], pca_SWAFR$x[, 1]), col = as.factor(data$QDS$region))
plot(data$QDS$QDS_richness ~ c(pca_GCFR$x[, 1], pca_SWAFR$x[, 1]), col = as.factor(data$QDS$region))
autoplot(pca_GCFR, loadings = TRUE)
autoplot(pca_GCFR, loadings = TRUE, loadings.labels = TRUE)
autoplot(pca_GCFR, loadings = TRUE, loading.labels = TRUE)
autoplot(pca_GCFR, loadings = TRUE, loadings.label = TRUE)
autoplot(pca_SWAFR, loadings = TRUE, loadings.label = TRUE)
autoplot(pca_GCFR, loadings = TRUE, loadings.label = TRUE)
