# Introduction

Biodiversity represents the variety of living things, and the variety of ecological and evolutionary processes responsible for it [@Bohn2004]. Studying the distribution of biodiversity in space is a major avenue of biological research [@Kerr2001; @Kreft2007]. Regional-scale geographic patterns in species richness have long been studied, particularly in biodiversity hotspots [@Cook2015]. The spatial distribution of species richness can be explained in terms of the physical environment. Properties of the environment have been suggested to influence species richness in three ways: (i) productivity, water, and energy to enable organismal growth, and resources (i.e. niche space) to support a wider range of species [@Kreft2007; @Gaston2000; @Mouchet2015]; (ii) stability, which enables species' persistence; and (iii) heterogeneity, which enables ecological speciation and possible barriers to gene flow, and with a wider variety of environments to facilitate species’ co-existence [@Thuiller2006; @Mouchet2015; @Cramer2016]. The physical environment, then, can be used to explain species richness in a local-deterministic sense, and in a historical context [@Ricklefs1987].

The maintenance of species richness, particularly the coexistence of high numbers of species in biodiversity hotspots, is often regarded as "paradoxical" [@Hart2017], and is a central problem in ecology [@Hart2017; @Kreft2007; @Ricklefs1987]. Species richness is constrained by the ability of habitats to support a variety of species---its ecological carrying capacity [@Mateo2017].
This is exemplified in approaches to modelling species richness as a function of environmental predictors in a correlative framework ["macro-ecological models"; @Mateo2017]. Macroecological models of species richness implicitly assume that communities are saturated, following species-area and species-energy relationships, and at equilibrium with the environment [@Mateo2017]. <!--Whether these assumptions are valid remains debated [@refs; @SDM_aliens_ref; @SDMs_et_al_refs]. Despite this, correlative approaches are a useful tool when first researching specific questions concerning species richness and environmental conditions.-->

A solution to the paradox of species coexistence is environmental heterogeneity (EH): a more heterogeneous environment has a larger environmental space, and can thus facilitate co-existence between species at the scale of that heterogeneity. EH can also stimulate ecological speciation, should the region be environmentally stable over evolutionary time-scales. Heterogeneity in the physical environment is known to be positively associated with species richness [@VanRensburg2002; @Hart2017], and has been demonstrated to do so across many taxa---e.g. Canadian butterflies [@Kerr2001], European vertebrates [@Mouchet2015], South African birds [@VanRensburg2002], in communities along marine continental margins [@Levin2010], French scarab beetles [@Lobo2004], and for global terrestrial plants [@Kreft2007]. The spatial scale of heterogeneity, or "grain" of the environment, is important to consider [@Hart2017], in the same way that the spatial of absolute environmental conditions has also been considered [@Baudena2015; @Mouchet2015; @Kerr2001]. Species co-existence and biodiversity maintenance is indeed suggested to be scale-dependent [@Hart2017].

EH is often under-represented in macro-ecological models of species richness, and has recently been found to explain up to ca. 95% of biome level species richness across South Africa [@Cramer2016]. Models that include EH yield better estimates of the richness of the Cape flora, as they account for the role heterogeneous environments such as those in the Cape facilitate species coexistence [@Cramer2016; @Thuiller2006]. Mediterranean-type terrestrial biodiversity hotspots, such as the Cape flora included in the models by @Cramer2016, present interesting study systems in which to investigate the relationship between the environment and species richness. These systems exhibit far greater species richness than predicted by their areas, productivities and latitudes [@Kreft2007; @Cowling1996]. There are five Mediterranean biodiversity hotspots on Earth: the California Floristic Province, the Mediterranean Basin, the Chilean Winter Rainfall-Valdivian Forests, the Greater Cape Floristic Region, and the Southwest Australia Floristic Region [@Cowling1996; @Hopper2004; @Cook2015]. These ecosystems have regular fire-cycles [@Cowling1996], climatic buffering, and long term stability [@Kreft2007], shrubby, sclerophyllous flora [@Hopper2004]. Together, they account for ca. 20% of global vascular plant species, yet only ca. 5% of global land surface areas [@Cowling1996]. Various hypotheses have been proposed to explain the high levels of plant species richness in these regions [@Cook2015]. The species accumulation hypothesis states that the stability of these regions has allowed many species to accrue. The species co-existence hypothesis states that these hotspots may facilitate greater degrees of species co-existence in smaller spatial areas, due to fine-scale heterogeneity in their environments. Indeed, EH has evolutionary implications too, stimulating ecological speciation across sharp environmental gradients.

Both the Southwest Australia Floristic Region (SWA) and the Greater Cape Floristic Region (Cape) are Mediterranean-type biodiversity hotspots, particularly in terms of plant species. Where the Cape (with an area of ca. 189,000 km^2^) is known to contain about 11,400 plant species (about 0.060 species per km^2^), SWA (area of ca. 270,000 km^2^) has about 3,700 species (0.014 species per km^2^) [@ManningandGoldblatt2012]. So, the Cape has ca. 4.3 times as many species per km^2^ as SWA. The Cape and SWA are appropriately often compared, due to the similarities between their environments (e.g. oligotrophic soils, an oceanically buffered moderate climate) and their plants' ecologies [@Hopper2004]. These two regions present unique flora out of the five Mediterranean systems, with high levels of endemism [@Cowling1996], and many obligate fire-adapted species [@Cowling1996]. Similarities withstanding, SWA is topographically and edaphically distinct from the Cape. The former is topographically rather uniform (i.e. flat)---uniquely so among the world's five Mediterranean-climate regions [@Hopper2004]). SWA possesses a mesoscale chronosequence dune system [@Cook2015; @Laliberte2014], while the Cape is mountainous, topographically heterogeneous, and therefore associated with a large degree of spatial climatic variability, with a fine-scale mosaic of geologies and soils [@Verboom2017; @Cramer2014; @Cowling1996]. <!--TODO: Mike: I think you need to a bit more specific about the origins of the soils and the geologies.
Just a sentence or so-->

Both regions have sources of edaphic heterogeneity, but at different scales. This edaphic variability may aid in explaining the species richness in these regions [@Beard2000; @Verboom2017]. EH can stimulate ecological speciation, should the region be stable over evolutionary time-scales, as is likely the case in both the Cape and SWA [@Hopper2004; @Lambers2010; @Wardell-Johnson1996; @Cramer2014; @Laliberte2014; @Cook2015]. For the Cape, this richness is largely known to result from long term climatic stability, and fine grain variation in geology and soils [@Cramer2014]. The question thus arises whether heterogeneity is a significant contributor to SWA species richness as is likely the case in the Cape. In the absence of topographic variability in SWA, it is proposed that the heterogeneity of that region is due to the juxtaposition of soil types [@Cook2015; @Laliberte2014], creating extreme edaphic variation.

## Hypothesis-v1

Our main hypothesis is that the greater abiotic heterogeneity in the Cape, and the finer grain of that heterogeneity, compared to that of the SWA, accounts for the Cape's greater species richness per unit area.
We expect the relationships between EH, species richness, and species turnover in these two regions to demonstrate this.
As stated above, heterogeneous environments can (i) support diverse species assemblages, and (ii) stimulate ecological speciation.
Thus, we expect species richness to covary with heterogeneity.
Additionally, as one moves across a heterogeneous landscape, we expect to find greater turnover in community composition, as different environments support different species.
Thus<!--As our effort here is towards explaining the species richness of these two floras, we also explore how species richness may covary with species turnover---such that -->, areas of greater turnover should also be more rich, due to potential complementarity between neighbouring communities increasing total richness<!--There exist two hypothetical extremes for a rich community: Hence, we also investigate the whereh on ther contiuum of dissimilar lw richess to similar high richness-->.
Thus, we expect that EH positively influences species richness and species turnover, and that species turnover itself positively influences species richness.<!--Consequent to the Cape's greater heterogeneity, we expect to find quantifiably greater species turnover between areas in the Cape.
This would concur with the Cape's greater species richness, as EH may not only support species rich Cape assemblages, but a diversity of complementary assemblages in the Cape-->

## Hypothesis-v2

Aim: This study investigates the role EH plays in explaining vascular plant species richness in the Cape and SWA.
We compare the relative importance of heterogeneity between the two regions, as heterogeneity has the evolutionary role of facilitating speciation, and the ecological role of supporting diverse species assemblages.
Spatial scale of that heterogeneity is also considered, as the heterogeneity-richness relationship can vary with habitat grain-size.
<!--TODO: ref this above!-->

Our hypotheses concern the Cape and SWA's environments and floras.
Our main hypothesis is that the Cape possesses greater abiotic heterogeneity, and at finer grain, compared to SWA, such as to explain the Cape's greater species richness per unit area, and proposed greater levels of species turnover between areas.
We also conjecture that the heterogeneity that predicts species richness in SWA will be more pronounced in terms of edaphic variables.
Here we attempt to assess six key predictions of this hypothesis, additionally investigating a seventh prediction to test the conjectured role of edaphic heterogeneity in SWA.
Dealing with the two regions' environments, we assess (i) whether the Cape environment is more heterogeneous than that of SWA and (ii) whether the Cape environment has more pronounced heterogeneity at finer scales than that of SWA.
Dealing with the distribution of species in the two regions, we assess (iii) whether the Cape exhibits greater levels of species turnover between areas.
Relating each regions' environment and flora, we finally assess (iv) whether species richness and species turnover are adequately predicted by EH in both regions and whether (v) Species richness and species turnover are better predicted by different forms of EH in either region (e.g.
the importance of edaphic heterogeneity in SWA).

...

We employ classical statistical methods to analyse publicly available geospatial and species occurrence datasets.

<!--(from A3 mindmapping)
NOTE: Generally, I wish to:
  1. Compare collinearity of:
    1.1 Elevation (= topography) w/ other variables
    1.2 Elevational roughness w/ other variables' roughnesses
  2. Compare models of richness/turnover as a function of:
    2.1 Elevation + elevational roughness
    2.2 Other variables + their roughnesses
    2.3 Elevation + elevational roughness + Other variables + their roughnesses
  3. Do the models in 2. in a:
    3.1 Linear regression framework
    3.2 Geographically weighted regression framework (e.g. Di Vigiolo et al. 2018 J Arid Enviro)
NOTE:
  - "Niche space" idea encapsulated by richness ~ EW
  - "Resource/support" ideas by richness ~ E
  - "Enviro filtering" ideas by turnover ~ EH
-->

<!--From BIO3013F Protea-SDMs project intro-->

...

Species distribution models (SDMs), or environmental niche models, are sets of empirical methods that relate observed species presences (or similar data) to environmental and spatial variables, often correlatively (Guisan & Thuiller, 2005). As SDMs rely chiefly on correlating observed species ranges with the conditions thereof, they provide only a model of the realised niche of a species (Raes, 2012), which can cause issues when attempting to predict responses of species to changing climate. Other assumptions of typical SDMs include that the range of species considered is in equilibrium with the environment (Altwegg et al., 2014; Guisan & Thuiller, 2005; Hannah et al., 2005), thus limiting the efficacy of these models on dynamically ranged or highly vagile species (Hannah et al., 2007). Regardless, given the dynamic nature of biotic ranges under climate change, SDMs are a valuable tool in identifying the contemporary risks posed to global and regional biodiversity.

The GCFR is a megadiverse terrestrial biogeographic region, with high levels of endemism. Midgley et al. (2003) investigated the responses the now defunct Cape Floristic Region (CFR) flora to climate change. Using bioclimatic envelope models (a form of SDM), they modelled the Fynbos Biome’s distribution as a whole, and select Cape-endemic Proteaceae species’ distributions, under current and future climate (climate scenario HadCM2), and again with the impact of land use change. Their Fynbos model was an indicator of regional priority for species level modelling efforts, showing a general southwards contraction of the biome. Their specific Proteaceae models yielded various results: complete extinctions for some species, range contractions for most, improbable range shifts in some, and range expansions in few. The range shifts predicted therein were acknowledged to be improbable, due to the unmodelled limitations of plant dispersal and edaphic dependence. Midgley et al. (2003) concluded that climate change is likely to have severely negative for the CFR flora. However, as will be outlined below, their methods may be overpredicting losses due to climate change.

...

The last 20 years have seen much ecological research interest in and development of SDMs, using many statistical and machine-learning-based methodologies (Altwegg et al., 2014; Elith et al., 2008, 2011; Guisan & Thuiller, 2005). Machine-learning-based methods in SDMs include MaxEnt (Elith et al., 2011), genetic algorithms, and adaptive neural networks (Hannah et al., 2005). The use of more advances statistics (e.g. Bayesian frameworks, ordination methods (Hannah et al., 2005)) is also seen. These two avenues of research have intersected in the development of boosted regression trees (BRTs) (originally “gradient boosting machine”; Friedman, 1999) a system of recursively generated, non-linear regression trees, as outlined by Elith et al. (2008). BRTs have been used as SDMs in southern Africa before (e.g. Thuiller et al., 2006), sometimes for conservation purposes (e.g. Coetzee et al., 2009), but BRTs have yet to be used specifically to assess the responses of the regional flora to climate change. BRTs have more flexibility in their predictions than more traditional methods (e.g. GAMs), as they are non-linear and machine-learning-based (Elith et al., 2008).

...
