# Materials and methods

```{r}
# FIXME: get richness numbers in text
#richness <- readr::read_rds(here::here("outputs/richness.RDS"))
# For now:
fixme <- list(GCFR = "FIXME", SWAFR = "FIXME")
richness <- list(
  n_before_checks = fixme,
  n_bad_names = fixme,
  n_final = fixme
)
```

## Overview

Our analyses defined boundaries for each region, those regions' environmental data and geospatially-explicit vascular plant occurrence records, all based on publicly available data. The environmental variables chosen (Table \@ref(tab:data-sources)) for this study were intended to cover a reasonable spread of climatic, edaphic, and ecologically relevant environmental axes, and are not intended to be exhaustive. We selected variables describing topography (elevation), productivity (NDVI), soil status and climate and climatic seasonality.

We carried out this investigation at four principal spatial scales: 0.05ยบ x 0.05ยบ squares (the finest common resolution among the environmental data sources used), quarter degree squares (QDS) [@Larsen2009], half degree squares (HDS) [@Larsen2009] and three-quarter degree squares (3QDS). For the Cape, most plant occurrence records are only accurate to QDS level. Thus, analyses involving species occurence data were necessary limited to scales including and above QDS.

Analyses were performed in R v3.4.0--3.5.1 [@RCoreTeam2018]. Version-numbers of specific R packages used are presented in the bibliography.

## Environmental data sources

The GCFR was treated as the areas occupied by the Succulent Karoo and Fynbos biomes in the current delineation of South Africa's biome boundaries [@Mucina2006]. The SWAFR was treated as the areas occupied by the Southwest Australia savanna, Swan Coastal Plain Scrub and Woodlands, Jarrah-Karri forest and shrublands, Southwest Australia woodlands, Esperance mallee, and Coolgardie woodlands in the World Wildlife Fund Terrestrial Ecoregions dataset [@Olson2001] in order to closely match the currently delineated SWAFR [@Gioia2017, @Hopper2004]. For the sake of readability, we shall refer to the GCFR and SWAFR simply as the Cape and SWA from hereon.

Geospatially-explicit raster layers were acquired for a selection of environmental variables (Table \@ref(tab:data-sources)), for the regions of interest. Raster data were re-projected to a common coordinate reference: WGS84 [@WGS84], using the "rgdal" [@Bivand2017] package in R [@RCoreTeam2018]. All data were re-sampled to 0.05ยบ resolution using the "resample" function in the R package "raster" [@Hijmans2016], with the "bilinear" method.

An emphasis was made on using satellite-derived environmental data in this work, in order to minimise differences in data quality and methodologies between the Cape and SWA. Additionally, satellite-derived data have been shown to benefit regional-scale species distribution models [@Deblauwe2016], thus motivating their use in this regional-scale study. The environmental data used in this study were derived from NASA's SRTM digital elevation model [@Farr2007], NASA's MODIS/Terra spectroradiometric data for land surface temperature and NDVI, the Climate Hazards Group's CHIRPS rainfall dataset [@Funk2015], and the International Soil Reference and Information Centre's SoilGrids250m edaphic dataset [@Hengl2017] (Table \@ref(tab:data-sources)). SRTM and MODIS are entirely derived from satellite measurements, whereas CHIRPS is interpolated from weather station data with satellite-derived radiometric measurements. SoilGrids250m is a machine-learning derived product, based on soil measurements as a function of many covariates, including MODIS and STRM sources [see @Hengl2017], using random-forests and other classification-tree-based methods, including gradient-boosting. For the soil data considered here (Table 1), we used depth-interval weighted average values as the value for a particular soil variable in a given place.

Climatic and spectral data arise from satellites monitoring properties of the Earth's surface through time. We therefore use the mean annual values for rainfall, surface temperature, and NDVI in each pixel in our analyses. Pronounced seasonality of rainfall is a known feature of mediterranean systems [@ref]. We describe this seasonality by computing computing the precipitation in the driest quarter (PDQ), using methods based on the "biovars" function in the R package "dismo".

## Plant occurrence data

<!--Download-->

Geospatially-explicit records of vascular plant occurrences were downloaded from the Global Biodiversity Information Facility (GBIF, Table \@ref(tab:data-sources)). Queries were made for tracheophyte records from within the borders of the Cape and SWA as treated here [@GBIFCape, @GBIFSWA]. Only records with defined species and intra-specific ranks were kept. Intra-specific occurrences were treated as simply being representative of their species. This resulted in `r richness$n_before_checks$GCFR` unique species names in the Cape, and `r richness$n_before_checks$SWAFR` in SWA.

<!--Remove bad names-->

We cleaned these data using the R package "taxise" [@Chamberlain2016, @R-taxize] to check that these species names had accepted-status among taxonomic databases. We queried two major taxonomic databases: the Global Name Resolver (GNR)<!--TODO: ref--><!--which includes the following independent databases within its queries: NCB, BoLD, ITIS, BHL, EoL, Redlist, GROMS, RAMSAR, BIRDLIFE or other conservation related indices, Scratchpad, LifeDesk indices, Tropicos, Exemplar online Flora and Fauna, and Fauna Europaea (<https://github.com/GlobalNamesArchitecture/gni/wiki/Sources>)-->, and the Taxonomic Name Resolution Service (TNRS)<!--TODO: ref--><!--. TNRS was built upon existing programmes from GNR, and includes a different (but not completely exclusive) set of databases (<http://tnrs.iplantcollaborative.org/sources.html>): Tropicos, The Global Compositae Checklist (GCC), USDA's Plants Database, NCBI, The International Legume Database and Information Service (ILDIS), The Plant List (Kew, Missouri Bot. G.) (TPL), But without Fabaceae and Asteraceae (see IDLIS, GCC)). The near-comprehensive coverage of the GNR and TNRS services combined motivated their use here. Each unique species name from the GBIF-derived list for each region was queried against GNR and TNRS. My implementation [TODO: please choose a different word here] to remove unaccepted names was forgiving [TODO: reword]-->. Should either one of these services return at least one match for a given name, then that name was accepted. Those names for which no full binomial matches were found in either database were excluded from the final list of species. The number of species names excluded totalled at `r richness$n_bad_names$GCFR` and `r richness$n_bad_names$SWAFR` for the Cape and SWA respectively. Especially for SWA, these numbers may be deemed appreciably high. But, the occurrence records that would be dropped, as a consequence of these names' removals, appeared randomly distributed in geographic space in both regions<!--TODO: make this map? or at least quote a stat..?-->. As such, any effect of the loss of these records in this analysis is likely uniform within the two regions.

<!--Correct for synonymy-->

After the unaccepted names were removed, it was important to ensure that a species was not listed under multiple synonyms. Such cases would skew estimates of species richness and turnover in this study. In light of this, the remaining names were queried in the Tropicos and Integrated Taxonomic Information System (ITIS) databases for their known synonyms, again using "taxize". These were collated to produce a nomenclatural "thesaurus" for the Cape and SWA species. This consisted of a list of the accepted species names in a region, each associated with a list of known synonyms. We amended species' names in the GBIF occurrence data, in order ensure species were listed under only one of these synonyms, replacing all appearances of a species' synonyms with the first synonym used in the list.

<!--Remove aliens-->

Lastly, We removed any species from both regions that are invasive aliens or non-indigenous. Alien species lists for plants in South Africa and Australia were acquired from the IUCN's Global Invasive Species Database (<http://www.iucngisd.org/gisd/>).

<!--Final lists and rasters-->

The final total plant species richness in each region was `r richness$n_final$GCFR` and `r richness$n_final$SWAFR` for the Cape and SWA respectively. These final collections of species occurrence records were converted to raster-layers, wherein pixel-values represented the species richness of vascular plants within that pixel. These rasters were produced at QDS, HDS, and 3QDS<!--TODO: 3QDS BRTs(?)--> resolutions.

## Analyses

### Quantifying environmental heterogeneity

In order to assess predictions (i) and (ii), we needed to describe the EH in both regions. Using the R package "raster" [@Hijmans2016], we used a modified version of the "roughness" index in the "terrain" function. For a three by three neighbourhood $\textbf{N}$ of cells, our index of roughness $R$ is the average square-root of the squared difference between each of the $n$ neighbour cells' values $x_i$ and the central focal cell's value $x_{\mathrm{focal}}$:

\begin{equation}
  R(\textbf{N}) = \frac{1}{n} \sqrt{
    \sum_{i=1}^n
    \left( x_{\mathrm{focal}} - x_i \right)^2
  }
  (\#eq:roughness)
\end{equation}

This value, notionally equivalent to the standard deviation of values relative to the focal value, is ascribed to the focal cell. Note, in order to use as much data from within regions' borders as possible, roughness was computed if a focal cell had at least one neighbour cell<!--Not necessary: "---that is, roughness is defined where $n_{x_{\mathrm{focal}}} \geq 1$"-->. Using this index, we produced raster layers of each of our nine environmental variable's heterogeneity. We compared the distributions of "roughness" values in each variable in each region with non-parametric Mann-Whitney $U$-tests, as almost all variables were highly non-normal, and could not be normalised by log-transformations. We also compare the effect size of the Cape vs SWA using the "common language effect size" ($CLES$), using the R package "canprot". The $CLES$ is the proportion of all pairwise comparisons between two sample groups' observations where one group's value is greater than the other's. We calculated the $CLES$ as the proportion of pairs where Cape roughness values were greater than that of SWA. This allowed us to assess prediction (i). To compare the spatial scales of heterogeneity (prediction (ii)) between each region, we repeated this analysis at all four spatial scales. This entailed recalculating the roughness layer for each variable after the original layer (0.05 degrees resolution) had been rescaled to each of the coarser resolutions.

### Quantifying species turnover

Regarding prediction (iii), we wished to compare the general degree of species turnover in each region. To compare the extent of species turnover between the Cape and SWA, we determined two metrics of species turnover. The first, computes the mean species turnover as Jaccard distances [@R-vegan] between each pair of QDS within each HDS ($\overline{J}_{\mathrm{QDS}}$, based on HDS with $2 \leq n \leq 4$ QDS) in both regions. The second is defined in terms of Whittaker's additive definition of $\beta$-diversity [@NBref], as follows:

\begin{equation}
  \gamma = \alpha + \beta
  (\#eq:whittaker)
\end{equation}

Here, we treat species richness at the HDS-scale ($S_{\mathrm{HDS}}$) as $\gamma$-diversity and at the QDS-scale ($\overline{S}_{\mathrm{QDS}}$) as $\alpha$-diversity. Intuitively, the species richness of an area is the result of some combination of the richness of sites within that area and the difference in species complements between those sites. Thus, we partition $\gamma$-diversity as in Equation \@ref(eq:whittaker), such that $\beta$-diversity is the difference between $\gamma$- and $\alpha$-diversity. We compare the distributions of $\overline{J}_{\mathrm{QDS}}$ and $T_{\mathrm{HDS}}$ using non-parametric Mann-Whitney $U$-tests, in order to guard against non-normality.

### Predicting richness and turnover with environmental heterogeneity

<!--Preamble-->

Regarding prediction (iii), we wished to compare the general degree of species turnover in each region. For (iv) and (v) we modelled species richness ($S$) and turnover as a function of various combinations of environmental and environmental heterogeneity variables in both regions using boosted regression-tree (BRT) modelling techniques. This allowed us to explore which axes of environmental heterogeneity are most influential on vascular plant species richness and turnover, and the differences in the importance of such axes between the Cape and SWA.

<!--What are BRTs?-->

BRTs are a flexible machine learning-based model of response variables and do so without involving normal null-hypothesis significance testing [@Elith2008], and have been employed previously to model species richness [see @Mouchet2015; @Thuiller2006; @Cramer2016] as macro-ecological models. BRTs are developed through the iterative generation of non-linear regression trees. BRTs are an ensemble-approach, in which a prediction $\widehat{y_i}$ is based on the weighted sum of the predictions of progressively "less important" regression trees ($t_k$), as opposed to the predictions of one tree [@Elith2008]. For $k \rightarrow nt$ number of trees, where each tree is itself a function of the matrix $\textbf{X}$ of $j$ predictor variables ($t_k = f(x_{ij})$), a BRT-model can be represented as follows:

\begin{equation}
  \widehat{y_i} = \sum_{k=1}^{nt} w_k t_k
  (\#eq:BRT)
\end{equation}

BRTs have two major meta-parameters over which users have control [@Friedman2001AnnStatistics]: the learning rate ($lr$, the rate at which iterative trees reduce predictive deviance during model-training, <!--conceptually a "shrinkage factor"--> controlling the contribution of each tree to the final model) and tree complexity ($tc$, the number of nodes on a given regression-tree, i.e. the maximum interaction depth the model is permitted to fit).

<!--Our BRT-modelling approach-->

BRTs were implemented here to predict both vascular plant species richness and turnover in each HDS, as a function of environmental variables and environmental roughness values in those cells, as Gaussian responses<!--(Equations \@ref(eq:S-BRT),\@ref(eq:J-BRT))-->, thus resulting in two BRT-models for each region. We treated richness as $S_{HDS}$ and turnover as $\overline{J}_{\mathrm{QDS}}$. The natural logarithm of species richness was used, in order to satisfy the assumptions of a Gaussian response. Note, this is not strictly because BRTs have any parametric assumptions concerning the distribution of the response variable, but rather to aid in applying the Gaussian-family of BRT algorithms to the richness data available. Additionally, BRTs were implemented to predict vascular plant species richness at the QDS-scale ($S_{\mathrm{QDS}}$), thus resulting in a total of six BRT-models presented here.<!--TODO: 3QDS BRTs?-->

As recommended by @Elith2008, BRT models were trained on a set of non-collinear predictor variables using "gbm.step" in "dismo" [@Hijmans2017] and "gbm" [@ref]<!--ref = Ridgeway, 2007-->. Collinear predictor variables can skew the interpretation of results, as the relatively influence of mutually collinear variables is reduced. Collinearity among the nine environmental predictor variables and their respective nine roughness-equivalents was assessed using "removeCollinearity" in the R package "virtualspecies" [@Leroy2015] separately for each region, such that variables were no more than 80% collinear (Pearson's $r \geq 0.80$). When faced with a cluster of collinear variables, one variable was chosen manually therefrom. Where possible, the roughness-equivalent of an environmental variable was included if its absolute-equivalent could also be included. When interpreting the results of BRTs, it is important to consider the effects of the variables included as representative of the effect of the excluded variables with which it was found to be collinear.<!--e.g. any interpretation of the effect of SNDPPT on species richness would then be also considered to be descriptive of the effect of soil pH on species richness.--><!--TODO: expand and include final list of predictor variables in-text or as table--><!--TODO: add dendrogram figure? appendix?-->

<!--Iterative parameter optimisation (lr, tc, nt)-->

In order to select ideal $lr$ and $tc$ all models (described below) were trained on the final non-collinear predictor sets iteratively for 25 combinations of a range of $tc$ values (1 to 5) and a range of $lr$ values (0.01, 0.005, 0.001, 5 $\times$ 10^-4^, 1 $\times$ 10^-4^). The function "gbm.step" optimises the number of trees ($nt$) using cross-validation during model training [@Elith2008] by halting iteration when predictions begin to overfit. For all models, we used 10 cross-validation folds (i.e. use 10 different randomly selected training data sets), a tolerance-threshold of 0.001, a bagging-fraction of 0.75 (proportion of training data randomly chosen to generate each tree), and trained models starting with 50 trees, with each iterative step adding 50 trees at a time, up to a maximum of 10,000 trees. Following this iterative parameter optimisation, Gaussian BRT models were constructed with $tc = 3$ and $lr = 0.001$, along with the other settings described.<!--The models were developed with all variables (those retained, above) and then simplified using the protocol suggested by Elith et al. (2008) to retain the minimum number of variables contributing to the models, using "gbm.simplify" in "dismo".-->

The optimum configuration of $lr$ and $tc$ for the final model is a trade-off between model fit (e.g. pseudo-$R^2$; Equation \@ref(eq:pseudo-R2)) and complexity ($nt$). <!--TODO: Make SI with these results: As the effect of $nt$ on pseudo-$R^2$ and $nt$ is negligibly small (Figure \ref{r2_nt_lr_tc}A), or non-significant (Figure \ref{r2_nt_lr_tc}B),-->A $tc$ of 5<!--TODO: double check no.--> was chosen for the final model. This follows the recommendations of @Elith2008, where $lr$ and $tc$ are advised to be adjusted inversely. This was chosen in order to account for the complex interactions determining species richness. To avoid overfitting, an intermediate $lr$ of 0.001<!--TODO: double check no.--> was chosen.

### Assessing BRT-predictions' fit

BRT-model performance can be described by measuring the variance in a dataset a BRT-model has explained, quantified here by $R_{\mathrm{pseudo}}^2$, which is the proportion of null deviance $D_{null}$ explained by some model $i$. Formally, it is defined as follows:

\begin{equation}
  R_{\mathrm{pseudo}}^2 = 1 - \frac{D_i}{D_{\mathrm{null}}}
  (\#eq:pseudo-R2)
\end{equation}

The derivation of this metric is not easy to interpret, as it is not immediately clear what model deviance is<!--NOTE: Is is approriate to say I don't know what deviance is?-->. Alternatively, comparing expected (i.e. model-predicted) and observed data has more heuristic appeal. We employed this metric of BRT-model performance too. We regressed expected against observed richness and turnover, and calculated the $R^2$-value for those regressions (hereafter $R_{\mathrm{E-O}}^2$).

<!--Permuted and replicate BRTS-->

The BRT-model fitting algorithm contains intrinsic stochasticity, due to the random partitions made in a dataset during cross-validation. Though this randomness is usually negligible (e.g. variables' contributions vary from run-to-run by a few decimal places), we reran each of the six BRT-models (see above) 1000 times in order to account for this stochasticity. Where indicated, we either present the averages of these replicate-models' results or the results of a representative model from each set of replicates.<!--TODO: explain how a "representative" model was determined-->

In order to assess the reliability of the conclusions drawn from these models, we randomly permuted the response data ($S_{\mathrm{QDS}}$, $S_{\mathrm{HDS}}$ and $\overline{J}_{\mathrm{QDS}}$) with respect to the environmental and heterogeneity data, and reran all six BRT-models 999 times (with the final non-collinear predictor sets and preconfigurations above). This also allows us to remove any effect of spatial autocorrelation in generating the observed correlations between patterns of species occurrence and environment [@CramerVerboom2016], and to allow us to assess the significance of our results relative to a random null. For all six models, the majority of the 999 permuted models failed to find associations between the response and predictor variables. The results of those that succeeded to fit a model to completion (usually ca. 200 out of 999<!--TODO: expand, add actual numbers in figure-->) are presented. The replicate and permuted BRT-models were compared using various measures of model performance (above; $nt$, $R_{\mathrm{pseudo}}^2$ (Equation \@ref(eq:pseudo-R2)), $R_{\mathrm{E-O}}^2$) and the ranks of these values for each replicate BRT-model relative to the 999 permuted models for that region/scope.

<!--TODO: include this somewhere:
"$nt$, the number of regressions trees used in a BRT-model, which is a measure of the duration for which a model was trained before adding additional trees did not significantly reduce the unexplained deviance"
-->
