# Table captions {-}

```{r setup-table3, include=FALSE}
# Make Table 3 here, in addition to in _after-body.Rmd, to get AIC in-text
source(here::here("setup.R"))
import_objects(
  here::here("outputs/species-turnover-and-richness/")
)
tidy_terms <- c(
  "Intercept",
  "$log(\\overline{S_{QDS}} + 1)$",
  "$\\overline{J_{QDS}}$",
  "SWA",
  "$log(\\overline{S_{QDS}} + 1) \\times$ SWA",
  "$\\overline{J_{QDS}} \\times$ SWA"
)
species_model_table <- my_model_table(
  model = species_turnover_richness_HDS_m,
  tidy_terms = tidy_terms,
  AIC_table = species_HDS_AIC_table
)
```

Captions are also repeated alongside their respective tables for readability.

## Table 1 <!--FIXME: \@ref(tab:data-sources)--> {-}

(ref:data-sources)
Georeferenced vascular plant species occurence and environmental data sources used in this study.
Abbreviations are as follows: MAP, mean annual precipitation; PDQ, precipitation in the driest quarter; CEC, cation exchange capacity.

(ref:data-sources)

## Table \@ref(tab:turnover-vs-geodist-model-table) {-}

(ref:turnover-vs-geodist-model-table)
Estimated coefficients and significances ($P$-value) following quantile regression of the 5%-quantile ($\tau = 0.05$) of pairwise vascular plant species turnover (Jaccards distance) as a function of the geographic distance (km, $log$-transformed) between QDS cells.
The Cape term represents the difference between Cape and SWA species turnover, for a given geographic distance.
<!--TODO: redo w/ Cape as baseline to match species-model-table-->
<!--TODO: embed within Figure 2-->

(ref:turnover-vs-geodist-model-table)

## Table \@ref(tab:species-model-table) {-}

(ref:species-model-table)
Estimated coefficients and significances ($P$-value) following multiple linear regression of HDS species richness against the mean QDS species richness ($log(x + 1)$-transformed) and turnover (Jaccards distance) within a given HDS, of the form in Equation \@ref(eq:S-HDS-formula).
The Cape was fit as the baseline, hence SWA represents the categorical term here.
<!--TODO: use SWA as baseline? to be more consistent w/ tab:turnover-vs-geodist-model-table-->
This was model was better fitting than a similar model without a region category ($\Delta AIC =$ `r species_model_table$deltaAIC`).
Note, this model does not represent those curves plot in Figure \@ref(fig:richness-vs-turnover) (there, the curves are from simple linear regressions of the variables in each panel, separated by region).

(ref:species-model-table)

## Table \@ref(tab:species-roughness-AICc) {-}

(ref:species-roughness-AICc)
Comparisons of Akaike information criterion values (small sample-size-corrected, $AICc$) of various geographically weighted regressions (GWR) of $log$-transformed species richness as a function of various sets of environmental variables.
Models were fit for the Cape and SWA richness and environmental data both separately and together.
GWR methods preclude the need for a categorical predictor for the Cape vs SWA, as the longitudinal (and to a lesser extent latitudinal) differences between the regions allows local regression coefficients in each region to differ.
<!--TODO: complete/expand: Models fit for each of the three geographic extents: null ($S_{ij} \sim \beta_{0}_{ij} + \beta_{1}_{ij} Lon_{ij} + \beta_{2}_{ij} Lat_{ij} + \beta\epsilon_{ij}$), ...-->

(ref:species-roughness-AICc)
