# Figure captions {-}

Captions are also repeated alongside their respective figures for readability.

(ref:roughness) Comparisons of different types of environmental heterogeneity between the the Greater Cape Floristic Region (Cape) and the Southwest Australia Floristic Region (SWA). We present (a) distributions of roughness values (Equation \@ref(eq:roughness)) for example variables from each broad category of the environment concerned. (b) The common language effect size ($CLES$; see text) of Cape versus SWA roughness values is shown for all variables, grouped by broad categories of the environment, describing differences in the distributions of Cape and SWA roughness values. We used Mann-Whitney $U$-tests to assess differences in these distributions. Non-significant differences ($P_U > 0.05$) are denoted as such ("NS"). Note, $U$-tests were performed using only a random set of 5000 cells at the 0.05-degree-scale<!--TODO: type egree symbol in on MacBook-->, as the $U$-test as implemented in R cannot handle more than that many values to compare.

Figure \@ref(fig:roughness): (ref:roughness)

(ref:turnover) Species turnover, described in two forms ((a) mean Jaccard distance between QDS in each HDS ($\overline{J}_{\mathrm{QDS}}$), (b) additively defined turnover ($T_{\mathrm{HDS}}$, Equation \@ref(eq:whittaker)) as a proportion of HDS richness ($S_{\mathrm{HDS}}$)), compared between the Cape and SWA. Mann-Whitney $U$-tests between the Cape and SWA distributions of $\overline{J}_{\mathrm{QDS}}$ and $T_{\mathrm{HDS}}$ yielded significant differences (see $P$-values and common language effect sizes ($CLES$) inset). <!--TODO: ammend panel b x-axis title to "T_HDS (as proportion of S_HDS)"-->

Figure \@ref(fig:turnover): (ref:turnover)

(ref:species-environment-relationships) Relative influence of environmental variables (including heterogeneity variables---prefixed with "R") in boosted regression tree (BRT) model predictions in the Greater Cape Floristic Region (Cape, a--c) and the Southwest Australia Floristic Region (SWA, b--d) of vascular plant species richness at the (b,e) QDS-scale ($= \overline{S}_{\mathrm{QDS}}$), (a,d) HDS-scale ($= S_{\mathrm{HDS}}$) and (c,f) turnover ($= \overline{J}_{\mathrm{QDS}}$). <!--Contributions here are treated as the relative influence (%) of variables on predictions [@Friedman2001AnnStatistics29(5):1189--1232].-->All BRT-models were permitted to fit three-way interactions between environmental variables<!--, with a learning rate of 0.001-->. Points denote the mean contribution of an environmental variable to model-predictions across the 1000 replicate BRT-models for that region/scope. Horizontal ticks denote the mean for the 999 permuted BRT-models. Standard deviations above and below these means are shown with vertical lines. Note, in the case of the replicate, standard deviations are so small such that the vertical lines are obscured by the points. Colours represent the general category of the environment to which a variable belongs (keyed), as in Figure \@ref(fig:roughness)b. Left-most piecharts inset in each panel display the same information. Right-most piecharts group contributions according to whether a variable was absolute or roughness-transformed (keyed). $F$-statistics inset are for one-way ANOVAs of differences in variables' relative influences---for both the replicate ($F_{\mathrm{rep.}}$) and permuted ($F_{\mathrm{prm.}}$) BRT-models.<!--Variables along the horizontal axes appear at least once in each panel (i.e. were retained in at least one of the four models) and are sorted in order of importance within each panel. Where variables did not contribute to a model, they are shown as zero.--><!--TODO: reword--> <!--TODO: move panel labels into panels, w/ response & regionas facet labels? might be less clear? at the very least, math-ify response names--> <!--NOTE: the colour scheme for the environmental variables is not colour-blind or BW friendly for these data-->

Figure \@ref(fig:species-environment-relationships): (ref:species-environment-relationships)

(ref:BRT-model-quality) Distributions of three measures of boosted regression tree (BRT) model performance: (a) the number of trees in the model $nt$, (b) $R_{\mathrm{pseudo}}^2$ (Equation \@ref(eq:pseudo-R2)), (c) $R_{\mathrm{E-O}}^2$ (see text). These measures are presented for the six sets of permuted (pale bars) and six sets of replicate BRT-models (dark bars) as in Figure \@ref(fig:species-environment-relationships), coloured according to the region of interest as in Figures \@ref(fig:roughness)a and \@ref(fig:turnover). In all cases, replicate BRT-models almost entirely out-rank the permuted models in terms of performance (Table \@ref(tab:BRT-quality-perms)) and the Greater Cape Floristic Region (Cape) and Southwest Australia Floristic Region (SWA) models had significantly different values for each metric (Table \@ref(tab:BRT-quality-regions)). Note, the actual differences between Cape and the SWA models' values is not realistically significant in some cases (e.g. the difference in $nt$ between the Cape and SWA QDS richness models is statistically significant, but are observedly so similar as not to affect interpretation)<!--TODO: expand-->.

Figure \@ref(fig:BRT-model-quality): (ref:BRT-model-quality)

(ref:BRT-variable-rank-concordance) Differences in the rankings of environmental variables' (including heterogeneity variables) relative influences on boosted regression tree (BRT) model predictions of vascular plant species richness and turnover in (a) the Greater Cape Floristic Region (Cape) and (b)<!--TODO: add lettering to panels--> Southwest Australia Floristic Region (SWA) (as in Figure \@ref(fig:species-environment-relationships)). Each point represents an environmental variable's rank in BRT-model importance, decreasing in importance from left to right. Rankings used here are the same as that of the average relative influence for variables across replicate BRT-models, presented in Figure \@ref(fig:species-environment-relationships). Coloured lines connect points representing the same environmental variable. Points' outlines are coloured according to the general category of the environment (keyed) to which a variable belongs, as in Figuress \@ref(fig:roughness)b and \@ref(fig:species-environment-relationships), while points' centres are coloured according to whether a variable was roughness-transformed or not. The comparisons of variables' rankings of interest are between QDS- and HDS-scale richness ($= \overline{S}_{\mathrm{QDS}}$ and $S_{\mathrm{HDS}}$ respectively; rows nos. 1 and 2) and between HDS-scale richness and turnover ($= \overline{J}_{\mathrm{QDS}}$) (rows nos. 2 and 3). Statistics ($\Delta$- and $P$-values) inset at the top and bottom of each panel refer to these comparisons respectively. $\Delta$-values represent the average absolute difference in ranks across variables between two models' rankings. The associate $P$-value results from ranking the observed $\Delta$-values against 999 $\Delta$-values based on random permutations of variables' rankings (SI1), such that more significant $P$-values denote rankings more similar than would be expected by chance. <!--TODO: add "(a)" and "(b)" as panel labels--> <!--NOTE: environmental variables' colour scheme not colour blind or BW friendly for these data--> <!--NOTE: This figure could be represented by a table. See e.g. table below-->


Figure \@ref(fig:BRT-variable-rank-concordance): (ref:BRT-variable-rank-concordance)

<!--
E.g. table version of fig:BRT-variable-rank-concordance

Region | Comparison    | Mean abs. diff. in ranks | P
-------|---------------|--------------------------|------
Cape   | S_QDS - S_HDS |                          |
       | S_QDS - J_QDS |                          |
       | S_HDS - J_QDS |                          |
SWA    | S_QDS - S_HDS |                          |
       | S_QDS - J_QDS |                          |
       | S_HDS - J_QDS |                          |
-->

(ref:environment-marginal-effects) Marginal effects of environmental conditions and heterogeneity on vascular plant species richness at the QDS-scale ($= \overline{S}_{\mathrm{QDS}}$; a,d), HDS-scale ($= S_{\mathrm{HDS}}$; b,e) and turnover ($= \overline{J}_{\mathrm{QDS}}$; c,f) in response variables in the Greater Cape Floristic Region (Cape; a--c) and Southwest Australia Floristic Region (SWA; d--f) following boosted regression tree (BRT) modelling. Marginal effect functions presented are derived from a representative BRT-model from the set of replicate BRT-models (for each of the six modelling cases) (see SI regarding how representative BRT-models were selected). Marginal effects represent the effect of a predictor variable when all other predictors are set at their means. Marginal effect functions are shown for environmental variables that contributed $\geq 10\%$ to a model's predictions. Functions are coloured as keyed, with solid lines representing absolute environmental variables and dotted representing heterogeneity variables ("rough"). Environmental variables were all rescaled here such as to be centred on zero (i.e. $Z$-transformed), facilitating comparison of functions' forms. <!--TODO: move panel labels into panels, w/ response & regionas facet labels? might be less clear? at the very least, math-ify response names--> <!--TODO: clean up legend labels (e.g. "rough_Soil.C" -> "R Soil C"--> <!--NOTE: environmental variables' colour scheme not colour blind or BW friendly for these data-->

Figure \@ref(fig:environment-marginal-effects): (ref:environment-marginal-effects)

<!--TODO: number SIs / choose SI structure-->

<!--TODO: add figure comparing distributions of observed and predicted richness and turnovers (boxplots like in Hons seminar)-->
