# Discussion

<!--Outline:

## Hypotheses/findings

Correct                         | Incorrect
--------------------------------|-------------------
EH                              |
$\beta$                         |
Types of EH: elevation, climate | Types of EH: soil

- Link to @Cook2015
  - @Cook2015 summarise the suites of hypotheses for the high levels of plant diversity in mediterranean-type ecosystems, regarding aspects of evolutionary diversification, ecological co-existence and time for species accumulation by either immigration or in situ evolution. Our study concens the dual role of EH in facilitating ecological speciation along environmental gradients and a diversity of habitats in wich greater numbers of species may co-exist. Regarding the former, ecological specialisation ... 
  - An avenue for future investigation may include quantifying associations between environmental stability and species richness and turnover (sensu that N American study), particularly regarding {inset info on Cape and SWA geologic/environmental evolution}.

## Caveats

1. Species turnover and richness issues
  - Species-area relationships etc.
    - Difficult to comment on unless I include the $\gamma = \alpha + \beta$ analyses
  - Additive vs multiplicative relationships between $\gamma, $\beta$ and $\alpha$
    - See comment on SARs above
  - Jaccard Index of turnover is richness-sensitive
    - Links to additive vs multiplicative problem above
2. Correlation issues
  - Spatial autocorrelation
    - In some senses _not_ an issue
      - Environmental data themselves
      - BRTs' CV procedure
      - Our permutation method
    - In other senses it _is_ an issue
      - Could counter-argue environmental data are spatially structured
      - Commonality of GWRs etc. in these sorts of studies
      - $\gamma = \alpha + \beta$ et al. would definitely(?) have this issue
    - E.g. sentence "As outlined by @Legendre1993, spatial autocorrelation is prevalent in ecological datasets and researchers must be cognisant of this in either their analyses or the interpretations of results."
  - Correlative framework of this study
    - Just talk about that a little...
3. Data quality issues
  - SoilGrids250m notoriously unreliable in regions of such complexity, due to
    - Being informed by poor sampling
    - Being ML-products themselves ("smearing" away regional patterns)
    - Perhaps this may be why we 
      1. Found soils less important in either region than we would expect
      2. Found soils as _completely_ unimportant in SWA
  - Temporal range of environmental data (and indeed floristic data) vastly less than the temporal scope of the research question (unavoidable I suppose?)
  - Herbarium vs inventory floristics
  - GBIF floristics

## Interpretations of our results

Environmental axis | Cape                    | SWA
-------------------|-------------------------|-----------------------
Productivity       | NB (discuss)            | NB (discuss)
Soil               | Conditions & variety NB | Nope... (see caveats)
Topography         | NB                      | Nope... (as expected)
Climate            | Somewhat                | NB

- Comment on other studies/broader context here

## Implications

- Generality of S $\sim$ EH
- Conservation of diverse/mosaic/heterogeneous habitats very NB

## Future studies

- Better turnover index (see caveats)
- Unpacking $\beta$ into turnover s.s. and nestedness (sensu that other study...)
- Spatially explicit models (see caveats), sensu @Legendre1993
- Phylogenetic $\beta$, functional \$beta$
- Biome-boundary studies
-->

<!--## Referring back to the hypotheses-->

<!--### Overview-->

Here we have provided support for the hypothesis that the difference in plant species richness between the Cape and SWA is accounted for by the greater abiotic heterogeneity in the Cape. As expected, the Cape is shown to possess (i) a quantifiably more heterogeneous environment that is (ii) generally heterogeneous at a finer spatial scale than SWA, with (iii) greater levels of floristic turnover. We have shown that vascular plant species richness (iv) can be explained in terms of environmental conditions including environmental heterogeneity in both the Cape and SWA. Also, we have shown that (v) the sets of environmental axes that explain plant species richness differ between the Cape and SWA. These findings contribute towards an understanding of the ecological conditions associated with high levels of species co-existence in these two regions, and strengthens the generality of a positive relationship between EH and biodiversity.

<!--### Biologically relevant environmental differences betw. the regions-->

The Cape and SWA regions present differentiable environmental spaces, each with varying degrees of heterogeneity across spatial scales and environmental axes. The clear distinction of the regions' topographic features is as expected [@fig-ref]. The Cape region has been found previously to have the second highest median topographic heterogeneity of the five Mediterranean-climate regions [@Bradshaw2014]. In the models developed by @Cramer2016 for South Africa, roughness in topography was largely superseded as an important predictor of species richness by other roughness variables. This is the case with our results too, likely as topographic complexity can be considered a proxy for gradients in other environmental axes, such as rainfall or temperature [@ref]. In line with our hypotheses, a combination of absolute and heterogeneity variables are associated with species richness and turnover. These effects are region-specific, particularly in that patterns in the Cape are more strongly determined by edaphic conditions and EH while SWA patterns are more strongly determined by absolute environmetal conditions, particularly climate.

Comparing our models to those fit by @Cramer2016, we did not directly find spatial heterogeneity in NDVI to be an important determinant of species richness and turnover patterns in the Cape. Rather absolute MAP, which is collinear with absolute NDVI, was found to be important. This speaks to the relationship between vegetation productivity and climate, and how suitably productive habitats can foster more species [@ref]. An additional interpretation of spatial heterogeneity (and indeed absolute conditions) in NDVI is that of changing canopy-light contexts [@Cramer2016]. @Power2017 found that floristic turnover between biomes in South Africa to be associated with differences in biomes' leaf area indices. <!--TODO: expand/cont.-->
 
The importance of edaphic conditions in the Cape withstanding, we did not detect a similar importance of soil in SWA as anticipated. **Comment on SoilGrids here.**

