# Discussion outline

## Hypotheses/findings & interpretations (to be melded together)

### Hypotheses/findings

Correct                         | Incorrect
--------------------------------|---------------------------------------
EH                              |
$\beta$                         |
Types of EH: elevation, climate | Types of EH: soil, NDVI [@Cramer2016]

- Link to @Cook2015
  - @Cook2015 summarise the suites of hypotheses for the high levels of plant diversity in mediterranean-type ecosystems, regarding aspects of evolutionary diversification, ecological co-existence and time for species accumulation by either immigration or in situ evolution. Our study concens the dual role of EH in facilitating ecological speciation along environmental gradients and a diversity of habitats in wich greater numbers of species may co-exist. Regarding the former, ecological specialisation ... 
  - An avenue for future investigation may include quantifying associations between environmental stability and species richness and turnover (sensu that @PintoLedezma2018), particularly regarding {insert info on Cape and SWA geologic/environmental evolution}.

### Interpretations of our results

Environmental axis | Cape                    | SWA
-------------------|-------------------------|-----------------------
Productivity       | NB (discuss)            | NB (discuss)
Soil               | Conditions & variety NB | Nope... (see caveats)
Topography         | NB                      | Nope... (as expected)
Climate            | Somewhat                | NB

- Comment on other studies/broader context here

## Caveats (to be sprinkled through-out discussion)

1. Species turnover and richness issues
  - Species-area relationships etc.
    - Difficult to comment on unless I include the $\gamma = \alpha + \beta$ analyses
  - Additive vs multiplicative relationships between $\gamma, $\beta$ and $\alpha$
    - See comment on SARs above
  - Jaccard Index of turnover is richness-sensitive
    - Links to additive vs multiplicative problem above
2. Correlation issues
  - Spatial autocorrelation
    - In some senses _not_ an issue
      - Environmental data themselves
      - BRTs' CV procedure
      - Our permutation method
    - In other senses it _is_ an issue
      - Could counter-argue environmental data are spatially structured
      - Commonality of GWRs etc. in these sorts of studies
      - $\gamma = \alpha + \beta$ et al. would definitely(?) have this issue
    - E.g. sentence "As outlined by @Legendre1993, spatial autocorrelation is prevalent in ecological datasets and researchers must be cognisant of this in either their analyses or the interpretations of results."
  - Correlative framework of this study
    - Just talk about that a little...
3. Data quality issues
  - SoilGrids250m notoriously unreliable in regions of such complexity, due to
    - Being informed by poor sampling
    - Being ML-products themselves ("smearing" away regional patterns)
    - Perhaps this may be why we 
      1. Found soils less important in either region than we would expect
      2. Found soils as _completely_ unimportant in SWA
  - Temporal range of environmental data (and indeed floristic data) vastly less than the temporal scope of the research question (unavoidable I suppose?)
  - Herbarium vs inventory floristics
  - GBIF floristics

## Implications

- Generality of S $\sim$ EH
- Conservation of diverse/mosaic/heterogeneous habitats very NB

## Future studies

- Better turnover index (see caveats)
- Unpacking $\beta$ into turnover s.s. and nestedness (sensu that other study...)
- Spatially explicit models (see caveats), sensu @Legendre1993
- Phylogenetic $\beta$, functional \$beta$
- Biome-boundary studies
