---
title: "Environmental heterogeneity patterns plant species richness and turnover in two hyperdiverse floras"
author: "Ruan van Mazijk, Michael D. Cramer & G. Anthony Verboom"
date: "`r Sys.Date()`"
toc: false
bibliography: Cape-vs-SWA_manual-edit.bib
csl: journal-of-biogeography.csl
link-citations: true
mainfont: Times New Roman  # for PDF
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  eval = TRUE,
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  results = "asis",
  fig.pos = "H",
  out.width = "18cm"
)
```

Department of Biological Sciences, University of Cape Town, Rondebosch, South Africa

Corresponding author: RVM (<ruanvmazijk@gmail.com>, +27 21 650 3684)

ORCID nos.: RVM: 0000-0003-2659-6909, MDC: 0000-0003-0989-3266, GAV: 0000-0002-1363-9781<!--?-->

**Running title:** Environmental heterogeneity and plant species richness

<!--TODO: check "mediterranean" not "Mediterranean"-->

# Abstract {-}

<!--J Biogeog: 300 word abstract-->

**Aim:** <!--From ResearchGate project-->To quantify the explanatory power of environmental heterogeneity in predicting plant species richness and turnover in two mediterranean-type biodiversity hotpots, the southwestern Cape of South Africa and southwest Australia (SWA), due to habitat diversity's stimulating speciation and supporting diverse assemblages. In each region, we compare different forms of environmental heterogeneity, species turnover and the relative importance of different forms of heterogeneity better predict species richness and turnover. We expected the Cape to be more heterogeneous in most environmental axes, and at a finer grain, such that the consequent high levels of species turnover explain the Cape's greater species richness per unit area. We also conjectured that edaphic heterogeneity would be an important factor in predicting species richness patterns in SWA.

**Location:** The Greater Cape Floristic Region in southwest Africa (the Cape), and the Southwest Australia Floristic Region (SWA)

**Taxon:** Vascular plants
  
**Methods:** Geospatially explicit floral and environmental data, non-parametric statistics, boosted regression tree modelling
  
**Results:** The Cape is more environmentally heterogeneous and has higher levels of floristic turnover than SWA. We find that environmental heterogeneity is the main predictor of species richness in the Cape, and somewhat less so for SWA. Edaphic conditions are found to be of more biologically important in the Cape, though this is contingent on the quality of the data modelled.
  
**Main conclusions:** The Cape was found to have generally more environmentally heterogenous than SWA, though SWA does possess edaphic heterogeneity as great as that in the Cape at coarse spatial scales, and greater levels of floristic turnover in vascular plant communities between grid-cells than SWA. Vascular plant species richness and turnover in the Cape was associated more strongly with environmental heterogeneity than in SWA, and particularly edaphic heterogeneity, than species richness in SWA. In SWA, patterns of species richness and turnover are more strongly associated with climatic axes<!--NOTE: see Hopper (1979. _Ann. Rev. Ecol. Syst._) Re: SWA escarpment and coastal band climate-->. The relative strengths of association of different environmental variables with patterns of species richness and turnover was found to vary with spatial scale.

_Keywords:_ biodiversity, boosted regression trees, BRTs, environmental heterogeneity, fynbos, Greater Cape Floristic Region, kwongan, macroecology, species richness, species turnover, vascular plants, Southwest Australia Floristic Region

# Acknowledgements {-}

This work was funded by the South African Department of Science and Technology (DST) and the National Research Foundation (NRF) under the DST-NRF Freestanding Innovation Honours Scholarship (to RVM), and by the South African Association of Botanists (SAAB) Honours Scholarship (to RVM). Thanks go to the Department of Biological Sciences, University of Cape Town, for providing a 2TB external hard drive for local GIS data storage. Many computations were performed using facilities provided by the University of Cape Town’s ICTS High Performance Computing team (<http://hpc.uct.ac.za>).

<!--TODO: Notify these acknowledged parties of publication too-->

<!--
Abbreviations:
- Greater Cape Floristic Region (GCFR) (= "Cape")
- Southwest Australia Floristic Region (SWAFR)  (= "SWA")
- TODO: fiver percent degree square (i.e. 0.05º x 0.05º) (FPDS)?
- quarter degree square (i.e. 0.25º x 0.25º) (QDS)
- half degree square (i.e. 0.50º x 0.50º) (HDS)
- three-quarter degree square (i.e. 0.75º x 0.75º) (3QDS)
- environmental heterogeneity (EH)
- & environmental variables' abbreviations in Table \@ref(tab:data-sources).
-->

