# Discussion

Here we have provided support for the hypothesis that the difference in plant species richness between the Cape and SWA is accounted for by the greater abiotic heterogeneity in the Cape. As expected, the Cape is shown to possess (i) a quantifiably more heterogeneous environment that is (ii) generally heterogeneous at a finer spatial scale than SWA, with (iii) greater levels of floristic turnover. We have shown that vascular plant species richness (iv) can be explained in terms of environmental conditions including environmental heterogeneity in both the Cape and SWA. Also, (v) the sets of environmental axes that explain plant species richness differ between the Cape and SWA. These findings contribute towards an understanding of the ecological conditions associated with high levels of species co-existence in these two regions, and strengthens the generality of a positive relationship between EH and biodiversity.

@Cook2015 summarised the suites of hypotheses for the high levels of plant diversity in mediterranean-type ecosystems. Broadly, these biodiversity hotspots are thought to arise due to greater levels of evolutionary diversification, ecological co-existence and time for species accumulation by either immigration or in situ evolution. Our study concerns the dual role of EH in facilitating ecological speciation along environmental gradients and a diversity of habitats in wich greater numbers of species may co-exist. We have correlative evidence for these processes, in that EH was positively associated with high levels of species richness and turnover in both regions. Further research should be aimed at distinguishing the roles of ecological speciation and species co-existence associated with EH in mediterranean-type ecosystems. The role of environmental stability is relevant here [@Cook2015, Pinto-Ledezma et al., 2018<!--; @PintoLedezma2018-->], both by allowing more continuous species accumulation when habitats persists through geologic time and by allowing environmental gradients to be stable long enough for ecological speciation to occur (Pinto-Ledezma et al., 2018)<!--[@PintoLedezma2018]-->. In the contexts of the Cape and SWA, this long term environmental stability, and the stability of EH through time, is indeed expected to contribute to these regions biodiversity [@Cowling1996; @Hopper1979].

_Ed: I'd like to include more information on the landscape/geologic history of the regions here, and link this to the notion of environmental stability and "species accumulation", sensu Cook et al. (2015) and Pinto-Ledezma et al. (2018)._

The Cape and SWA regions present differentiable environmental spaces, each with varying degrees of heterogeneity across spatial scales and environmental axes. The clear distinction of the regions' topographic features is as expected. The Cape region has been found previously to have the second highest median topographic heterogeneity of the five Mediterranean-climate regions [@Bradshaw2014]. In the models developed by @Cramer2016 for South Africa, roughness in topography was largely superseded as an important predictor of species richness by other roughness variables. This is the case with our results too, likely as topographic complexity can be considered a proxy for gradients in other environmental axes, such as rainfall or temperature<!--@ref-->. In line with our hypotheses, a combination of absolute and heterogeneity variables are associated with species richness and turnover. These effects are region-specific, particularly in that patterns in the Cape are more strongly determined by edaphic conditions and EH while SWA patterns are more strongly determined by absolute environmetal conditions, particularly climate. @Kreft2007 modelled global terrestrial vascular plant species richness, which focussed primarily on using absolute environmental variables, underestimated the richness of the Cape flora. Though @Kreft2007 did include topographic heterogeneity in their predictor set, topography is often a proxy for more biologically meaningful variables [@Cramer2016]. This explains why the inclusion of these variables (e.g. roughness in mean annual precipitation) yields more accurate predictions of species richness. Indeed, @Thuiller2006 also included topographic heterogeneity.

We also detected strongly non-linear relationships between environmental and heterogeneity variables and species richness and turnover. We expected this, as non-linear relationships are common in ecology (Zanne et al. 2018)<!--[@Zanne2018]-->, making our use of machine-learning methods appropriate here.

Comparing our models to those fit by @Cramer2016, we did not directly find spatial heterogeneity in NDVI to be an important determinant of species richness and turnover patterns in the Cape. Rather absolute MAP, which is collinear with absolute NDVI, was found to be important. This speaks to the relationship between vegetation productivity and climate, and how suitably productive habitats can foster more species <!--@ref-->. An additional interpretation of spatial heterogeneity (and indeed absolute conditions) in NDVI is that of changing canopy light-contexts [@Cramer2016]. @Power2017 found that floristic turnover between biomes in South Africa to be associated with differences in biomes' leaf area indices. We found NDVI to be more heterogeneous across the Cape than SWA (Figures \@ref(fig:roughness)). NDVI is an integrating variable, which captures information about productivity, light availability, and soil nutrients [@Power2017]. Absolute NDVI and its correlates can be interpreted as contributing to predicting species richness in the Cape. This demonstrates the role of ecological productivity in facilitating the co-existence diverse species assemblages. EH, then, must be considered alongside resource- and energy-availability axes when intepreting the drivers of species richness. In so much as a diverse environmental space supports more species, the materials and productivity required for biota to thrive are also needed to support species [@Bohn2004; @Kerr2001; @Kreft2007; @Gaston2000]. As such, our findings, along with those of previous studies [@Cramer2016; @VanRensburg2002; @Thuiller2006; @Kreft2007], suggest that there are ecological and evolutionary consequence to both resource availability and EH.

<!--NOTE: link above more to biome boundary studies in future studies para below-->

<!--Old sentence:
The fact that thermal variables tend to be more rough in the Cape is likely due to possible covariance of the MODIS/Terra products with topography, as MODIS data used here describes land surface temperature. As the Cape is topographically rugged, the roughness of NDVI may arise from this. Despite this, ...
-->

We detected a strong set of links between various edaphic properties and vascular plant species richness and turnover in the Cape. The importance of absolute pH speaks to the association of many Cape communities with nutrient impoversished, acidic soils <!--@ref-->. We did not, however, find edaphic conditions to be as important as we expected in SWA. This may be due to a real lack of importance of edaphic features in driving assemblage patterns in SWA. ALternatively, there is a risk that the quality of soil data provided to our models, from SoilGrids250m <!--@ref-->, is insufficient for our purposes here. There are two potential reasons for this. Firstly, teh SoilGrids250m data product is acknowledged to be less accurate at the scales we investigate here <!--@ref-->, such that the true variation in soil properties in SWA is not represented in our dataset. Secondly, it could be that the link between soils and assemblage patterns in SWA exists, but simply at a finer scale than that at which we performed our analyses here. These two reasons are not mutually exclusive, in that SoilGrids250m may be both inaccurate at the scales we consider here and that our analysis considers scales greater than those important in SWA plant community assemblage patterns. This is particularly relevant to our study, as the Cape has a much wider range of scales exhibited in the heterogeneity across its environmental axes. Notably, each region has finer scale heterogeneity in some variables, and coarser scale in others---neither region is more fine or coarse than the other over all environmental axes.

_Ed: I'd obviously like to include more information on the landscape/geologic history of the regions here too, and with reference to particular soil variables (Mike?)._

Another issue related to spatial scales, as with any ecological study, is that of spatially uniform and representative plant species occurence data. Efforts were made herein to minimise differences in data-quality between SWA and Cape by using remote-sensing derived environmental data. Species occurence data, however, prove difficult to obtain with uniform methodology. South African biodiversity data is stored only to QDS-level accuracy. As such, our analyses were limited to that as the finest spatial scale, such that our environmental datasets necessarily, then, were also limited to the QDS-scale. This may complicate the interpretation of our analyses, as these data may be too coarse in scale to capture patterns of species richness and turnover and their associations with the environmenta in reality in empirically heterogeneous environments like the Cape and SWA.

In addition to the scale of our data, spatial bias in species occurence data must also be considered. GBIF data are sourced from both herbaria and plot-monitoring datasets. The relative contribution of each of these to GBIF data may vary between countries and regions---i.e. between the Cape and SWA. As recently noted by @Guerin2018, herbarium records and plot-based inventories describe regional flora with varying accuracy, especially with respect to documenting high levels of floristic turnover. We emphasise here our concerns that there the floral occurence data and soils information use in this study are especially at risk of spatial bias and/or inaccuracies.

<!--
Species-area relationships et al.
- $\beta$ = turnover + nestedness
- $\gamma = \alpha + \beta$ analyses and Whittaker and other defs of $\gamma$
- Jaccard distance is richnes dependent...
-->

_..._

Jaccard distances, as used here as $\overline{J}_{\mathrm{QDS}}$, are highly richness dependent. Although they represent the proportional floristic turnover between cells, this proportion itself is sensitive to the richness of sites under comparison. For example, the turnover between two low richness sites has is likely to be greater by chance, due to the absence or presence of a few species, than the turnover between two high richness sites, where the absence or presence of a few species does not greatly affect the turnover calculated.

_..._

<!--Old sentences/para (is this true?; note good refs in the end of this para):
BRT-models of species richness in both regions reveal species richness to depend on those environmental axes that differentiate the two regions (Figures \ref{richness_pred_obs}), \ref{BRT_contribs_summary}). The importance of variables is also shown to vary with spatial scale (Figure \ref{BRT_contribs_summary}), as previously suggested may be the case when modelling geographic patterns of biodiversity [@Baudena2015]. Indeed, as @Cowling1996 describes differing patterns of species richness across spatial scales, so do the predictors of those patterns vary with scale [@Hart2017].
-->

<!--TODO: perhaps repeat this little analysis on distributions of predicted and observed richness and turnover nos.:
Though the Cape was correctly predicted to have, on average, more species per grid-cell at HDS and 3QDS scales than SWA, this was not the case for QDS grid-cells (Table 5). This demonstrates that the Cape is indeed overall more rich in plant species than SWA, but a given HDS in SWA contains fewer species than a given Cape HDS. Thus, the greater richness in the Cape is a product of greater turnover in species at spatial scales no more coarse than the HDS. Species turnover is an interesting aspect to species richness studies, as it species turnover is implicit to species-area and co-existence-area relationships [@Hart2017]. One could expect patterns of endemism and species turnover to concur with patterns in environmental heterogeneity to some degree.
-->

<!--Correlative studies: a note-->

Our findings here are correlative. There are, however, many proposed mechanisms to explain the correlative signals demonstrated here. Our findings support the hypothesis that mediterranean systems' plant species richness is a function of spatial variability in environmental conditions. This can stimulate diversification, and maintain that diversity by providing a range of habitats for species co-existence. Oligtrophic soils can stimulate an increase in functional diversity, through the evolution of diverse nutrient acquisition strategies [@Lambers2010; @Verboom2017]---e.g. sclerophylly [@Cook2015; @Cramer2014]. An aspect of the environment I have neglected to consider is fire, shown to also contribute to predictions here in the Cape [@Cramer2016]. @Cardillo2012 have shown the structuring forces behind species co-occurrence patterns, and thus likely species richness,differ between species-pairs with different post-fire responses and those with similar post-fire responses.

<!--Spatial autocorrelation: a note:
As outlined by @Legendre1993, spatial autocorrelation is prevalent in ecological datasets and researchers must be cognisant of this in either their analyses or the interpretations of results.
-->

<!--Phylogenetic and functional richness and turnover and biome boundaries-->

Following from the understanding that functionally diverse assemblages, which are more likely to be more species rich, are likely to arise and/or occur in areas with diverse ecological pressures [@Molina-Venegas2015], one would expect, then, heterogeneous habitats such as those in Mediterranean-type biodiversity hotspots to exhibit high levels functional beta diversity along steep environmental gradients [@Molina-Venegas2015]. If the niches concerning these functions are phylogenetically conserved among those biota, then one would also expect high levels of species and phylogenetic beta diversity along these gradients [@Molina-Venegas2015]. This concurs with the notion put forward by @Power2017, wherein megadiverse systems such as these represent the results of "phylogenetic niche conservatism on a heterogeneous landscape". Thus, species and phylogenetic turnover should covary with environmental heterogeneity in some way. Indeed, endemism, at certain scales, could also follow this pattern. @Thuiller2006 demonstrated that there are phylogenetic and biome-related determinants of species richness. This makes sense in light of the low probability of lineages crossing biome boundaries in Mediterranean systems [@Power2017]. NDVI and light availability, and the heterogeneity therein, are associated with high levels of floristic turnover [@Power2017]. This may be indicative of ecological specialisation precluding species from crossing these boundaries, thus increasing the level of endemism within a region, while also increasing the level of turnover, and thus likely species richness, along environmental gradients. Although, this may be debated. @Beard2000 state that the high levels of endemism in SWA are function of habitat specialisation to soil mosaics. Cf. @Laliberte2014, who say that this endemism is likely due to environmental filtering along these soil turnover sequences, as opposed to the juxtaposition of specialised species along soil gradients.

_Ed: Is it worth expanding this discussion to functional diversity and phylogenetic diversity metrics too?_

<!--#FutureStudies: a list:
- 3QDS scale BRTs
- $S_{\mathrm{HDS}} \sim \overline{S}_{\mathrm{QDS}} + \overline{\delta_{ij}}_{??}$ (= "$\gamma = \alpha + \beta$"-analysis) (see `explore-turnover-metrics.pdf` note, where $\overline{\delta_{ij}}(\textbf{N})_{??} = \overline{\alpha_i}(\textbf{N}) \times \overline{\beta_{ij}}(\textbf{N}) = \overline{S}_{\mathrm{QDS}} \times \overline{J}_{\mathrm{QDS}}$)
- Expanding the analyses to other/all mediterranean-type regions
- Investigating environmental stability through time (e.g. WorldClim LGM vs today)
- Phylogenetics/mega-trees in different flora? $\beta_{phylo}$?
- Teasing apart co-existance and evolution
- Teasing about turnover into turnover-sensu-stricto and nestedness
- Functional diversity $\sim$ EH? Functional turnover?
-->

<!--Implications:
- Generalising $S \sim EH$ further
- Better understanding of mediterranean-type systems
- Conservation impact: habitat diversity NB [@refs (sensu "save more habitats save more species, duh")]
-->

<!--Conclusion-->

<!--Regarding the Cape, depending on whether one consults pseudo-$R^2$ (Table 3), the ratio of mean predicted to observed richness per grid-cell (Table 5), or the distributions of predicted vs. observed richness values per grid-cell (Figure \ref{richness_pred_obs}), I have achieved a similarly suitable level of predictive accuracy.--> <!--TODO: update w/ new results--> <!--There is, though, still unexplained species richness in light of my models. As @Cramer2016, @VanRensburg2002, @Thuiller2006, and @Mouchet2015 have done, these macro-ecological models are a-historical. Evolutionary considerations of species richness in geographic space are worthwhile, especially in regions with environments stable over evolutionary time.--> <!--TODO: expand-->

Summarily, we have demonstrated support for the generality of EH as a meaningful predictor of patterns of species richness and turnover in mediterranean-type ecosystems. In SWA and the Cape, high levels of are also likely the results of long-term landscape and climatic stability [@Hopper1979]. Thus, the roles of environmental variability through space that persists through deep time are two important ways in which the environment relates to biodiversity in these regions. The efficacy of environmental stability through geological time should be explored further, comparing the Cape and SWA.
