---
title: |
  | Choosing representative BRT-models
  | from sets of replicates
subtitle: |
  | Supplementary Information
  | Cape vs SWA publication
author: "Ruan van Mazijk"
date: "`r Sys.Date()`"
mainfont: Times New Roman  # for PDF
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.width = 6, fig.height = 3
)
library(here)
source(here("R/setup.R"))
```

```{r example, fig.cap="Example distribution of some BRT-model quality metric. Vertical dashed lines represent the 5% bound about the median metric value. A representative boosted regression tree (BRT) model from a set of replicates was determined as one which falls within the 5% quantile bound about the set's median values for all the various model-quality statistics ($nt$, $R^2_{\\mathrm{pseudo}}$, $R^2_{\\mathrm{E-O}}$). When more than one model was found to meet this criterion, one was chosen at random."}
set.seed(1234)
dbn <- tibble(x = rnorm(1000))
ggplot(dbn, aes(x)) + 
  geom_histogram(colour = "black", fill = "white") + 
  geom_vline(xintercept = qnorm(c(0.475, 0.525)), linetype = "dashed") +
  xlab("Quality metric value")
```
