\clearpage

# Appendix {-}

```{r}
compare_combined_region_models_for_appendix <- function(models,
                                                        response = NULL) {
  if (is.null(response)) {
    response <- unique(models$response)
  }
  
  # Get AICs etc.
  models_summary <- models %>%
    group_by(predictor) %>%
    mutate(aic = map_dbl(model, AIC)) %>%
    mutate(
      model_rank = as.numeric(region_term),
      delta_aic  = aic - min(aic),
      # Choose the "best" ^ "simplest" model
      best_model = (model_rank == min(model_rank[delta_aic < 2]))
    ) %>%
    ungroup() 

  # Make pretty
  models_summary_printable <- models_summary %>%
    mutate(
      predictor = predictor %>%
        str_remove("_roughness") %>%
        str_replace_all("\\.", " ") %>%
        factor(levels = c(var_names, "PC1")),
      region_term = case_when(
        region_term == "none" ~ "None",
        region_term == "add"  ~ "Additive",
        region_term == "int"  ~ "Interaction",
      ),
      best_model = ifelse(best_model, "*", " ")
    ) %>%
    arrange(predictor) %>%
    mutate_at(c("slope_p_value", "region_p_value", "int_p_value"),
      ~ case_when(
        .x < 0.001 ~ "***",
        .x < 0.010 ~ "**",
        .x < 0.050 ~ "*",
        .x < 0.100 ~ ".",
        TRUE       ~ " "
      )
    ) %>%
    mutate_if(is.numeric, ~ case_when(
      is.na(.x) ~ " ",
      TRUE      ~ format(round(.x, digits = 2), nsmall = 2)
    )) %>%
    mutate_if(is.character, ~ ifelse(is.na(.x), " ", .x)) %>%
    dplyr::select(
      predictor, region_term, delta_aic, best_model,
      slope,        slope_p_value,
      region_coeff, region_p_value,
      int_coeff,    int_p_value
    )

  # Remove variable names after first mention in table
  models_summary_printable$predictor %<>% as.character()
  for (pred in unique(models_summary_printable$predictor)) {
    to_remove <- which(models_summary_printable$predictor == pred)[-1]
    models_summary_printable$predictor[to_remove] <- " "
  }
  
  # Print summary table
  response <- case_when(
    response == "HDS_richness"      ~ "$S_{\\mathrm{HDS}}$",
    response == "QDS_richness"      ~ "$S_{\\mathrm{QDS}}$"
  )
  knitr::kable(models_summary_printable,
    caption = glue(
      "Results of separate simple linear regressions of {response} \\
      against environmental heterogeneity variables. Significance is denoted \\
      with asterisks as follows: \\
      \"\\*\\*\\*\", $P < 0.001$; \\
      \"\\*\\*\", $0.001 < P < 0.01$; \\
      \"\\*\", $0.01 < P < 0.05$; \\
      \".\", $0.05 < P < 0.1$; \\
      and non-significant results ($P \\geq 0.1$) being left blank."
    ),
    col.names = c(
      "Heterogeneity predictor", "Region-term",
      "$\\Delta AIC$", " ",
      "Slope",         " ",
      "SWAFR effect", " ",
      "Slope:SWAFR",  " "
    ),
    align = "llrlrlrlrl"
  )
}
```

```{r}
compare_combined_region_models_for_appendix(combined_region_HDS_models)
```

\clearpage

```{r}
compare_combined_region_models_for_appendix(combined_region_QDS_models)
```

\clearpage

```{r}
models_summary_printable <- models_summary %>%
  dplyr::select(response, term, estimate, p.value) %>%
  mutate(
    estimate = format(round(estimate, 2), nsmall = 2),
    response = case_when(
      response == "HDS_richness" ~ "$S_{\\mathrm{HDS}}$",
      response == "QDS_richness" ~ "$S_{\\mathrm{QDS}}$"
    ),
    sig = case_when(
      p.value < 0.001 ~ "***",
      p.value < 0.010 ~ "**",
      p.value < 0.050 ~ "*",
      p.value < 0.100 ~ ".",
      TRUE            ~ " "
    )
  ) %>%
  dplyr::select(response, term, estimate, sig)
```

```{r}
models_summary_printable %>%
  filter(response == "$S_{\\mathrm{HDS}}$") %>%
  dplyr::select(-response) %>%
  knitr::kable(
    caption = paste(
      "Results of multiple simple linear regressions of $S_{\\mathrm{HDS}}$",
      "against environmental heterogeneity variables. Significance is denoted",
      "with asterisks as follows:",
      "\"\\*\\*\\*\", $P < 0.001$;",
      "\"\\*\\*\", $0.001 < P < 0.01$;",
      "\"\\*\", $0.01 < P < 0.05$;",
      "\".\", $0.05 < P < 0.1$;
      and non-significant results ($P \\geq 0.1$) being left blank."
    ),
    col.names = c("Heterogeneity predictor", "Slope", " "),
    align = "lrl"
  )
```

```{r}
models_summary_printable %>%
  filter(response == "$S_{\\mathrm{QDS}}$") %>%
  dplyr::select(-response) %>%
  knitr::kable(
    caption = paste(
      "Results of multiple simple linear regressions of $S_{\\mathrm{QDS}}$",
      "against environmental heterogeneity variables. Significance is denoted",
      "\"\\*\\*\\*\", $P < 0.001$;",
      "\"\\*\\*\", $0.001 < P < 0.01$;",
      "\"\\*\", $0.01 < P < 0.05$;",
      "\".\", $0.05 < P < 0.1$;
      and non-significant results ($P \\geq 0.1$) being left blank."
    ),
    col.names = c("Heterogeneity predictor", "Slope", " "),
    align = "lrl"
  )
```
