---
output: 
  word_document:
    reference_docx : style.docx
bibliography       : Cape-vs-SWA.bib
csl                : journal-of-biogeography.csl
---

# Results

## Comparing regions' environmental heterogeneity

We compared both the various forms of EH's values and PC1 of EH between the GCFR and SWAFR using common language effect sizes (_CLES_; ref). The _CLES_ of GCFR vs SWAFR heterogeneity values was regressed against the spatial scale at which it was calculated using OLS linear regression (Figure 1). PDQ, NDVI, pH and, arguably, elevation (Figure 1a,c,e,i) are all consistently more heterogeneous in the GCFR than in the SWAFR, regardless of spatial scale. The GCFR is more heterogeneous at finer scales in terms of MAP, surface temperature, CEC and soil carbon (Figure 2b,d,f,h). Notably, the GCFR is more pronouncedly heterogeneous at broad scales in terms of clay (Figure 2g)---perhaps something to do with the Succulent Karoo vs CFR?. In general (see PC1; Figure 2j), the GCFR is more environmentally heterogeneous than the SWAFR, and particularly so at fine spatial scales. The GCFR is more finely scaled in its heterogeneity, though some variables show no scale-dependence, and heterogeneity in clay is greatest in the GCFR at broad scales.

## Comparing and decomposing regions' species richness

Using Whittaker's definition of additive turnover (ref), we partitioned _S_~HDS~ into it's $\alpha$- and $\beta$-components ($\overline{S}$~QDS~ and _T_~QDS~ respectively). Using this method, we can see that almost all HDS in both the GCFR and SWAFR are composed of QDS that only account for no more than ca. 50% of _S_~HDS~ (Figure 2a). Accounting for the generally greater _S_~HDS~ in the GCFR (Figure 2b), _S_~HDS~ in the GCFR is more attributable to floristic turnover than that in the SWAFR (Figure 2c).

## Environmental heterogeneity as an explanation of species richness

We regressed vascular plant species richness (_S_) against each axis of EH separately (Table 2, Figure 3) and in a multivariate model (Figure 4), at both HDS- (Table 2a, Figure 4a) and QDS-scales (Table 2b, Figure 4b). For each axis of EH, we fit three univariate models: _S_ as a function of EH, _S_ as a function of EH with an additive term describing region and _S_ as a of EH with an interaction term for region. We used Akaike's information criterion (_AIC_; ref) to select which of these three model types fit best for each EH predictor variable. In each case, the best-fitting model (those presented in Table 2) was selected as the simplest model with $\Delta$_AIC_ < 2---i.e. a more complex model was only justified when it had the lowest _AIC_-score by more than 2 _AIC_-units.

At the HDS-scale (i.e. for _S_~HDS~; Table 2a), there is evidence a difference in the slopes of the GCFR and SWAFR's relationships with heterogeneity in MAP. Heterogneity in NDVI and clay only present evidence for the same slope in each region, but differing intercepts. Heterogeneity in CEC and pH have non-significant slopes and signficiant region-effects---suggesting that these variables values' have weak relationships with _S_~HDS~, and that the region-effect explains more of the variance. Other variables (heterogeneity in elevation, PDQ, surface T and soil C) only present evidence for a continuous effect of that heterogeneity, explaining the difference in the regions' _S_~HDS~ in terms of the roughness values themselves, without the need to invoke a region term. Think of it this way:

- If there is no need for any information concerning the region a cell belongs to, then the environmental roughness "rule" is followed well across the two regions in a similar way.
- If the region-effect is significant, but not the roughness effect, then that roughness axis isn't doing a very good job of explaining anything, and must defer to the region-effect.
- When both the region- and roughness-effect are significant, this represents a softer version of the above, where the roughness axis can explain some variance, but not all.
- When there is a significant interaction between region and roughness, then each region is playing a whole new game with that axes in terms of how richness is being driven.

At the QDS-scale (i.e. for _S_~QDS~; Table 2b), it is noteworthy that all axes best-supported to have an additive region term only also had non-significant roughness-effects [expand?].

I also regressed against PC1. Like heterogeneity in elevation and surface T, PC1 was the only explanatory variable "needed" in regressions for _S_~HDS~ (also see Figure 3) and _S_~QDS~. Figure 3 shows quite nicely how, in general, the GCFR and SWAFR are following the same "rule" (species richness increases with increasing environmental heterogeneity (PC1)) but occupy different areas along that relationship (the GCFR being more rich and more rough than the SWAFR).

| Response     | Model type           | Heterogeneity predictor | Slope |     | SWAFR effect |     | Slope:SWAFR |     |
|:-------------|:---------------------|:------------------------|:-----:|:----|:------------:|:----|:-----------:|:----|
| (a) _S_~HDS~ | Main effect × region | MAP                     |   +   | *** |      +       |     |      -      | **  |
|              | Main effect + region | Clay                    |   +   | *   |      -       | **  |             |     |
|              |                      | NDVI                    |   +   | *** |      -       | *   |             |     |
|              | Main effect only     | Elevation               |   +   | *** |              |     |             |     |
|              |                      | PDQ                     |   +   | *** |              |     |             |     |
|              |                      | Soil C                  |   +   | *** |              |     |             |     |
|              |                      | Surface T               |   +   | *** |              |     |             |     |
|              |                      | PC1                     |   +   | *** |              |     |             |     |
|              | Region only          | CEC                     |   -   |     |      -       | **  |             |     |
|              |                      | pH                      |   +   |     |      -       | **  |             |     |
| (b) _S_~QDS~ | Main effect × region | NDVI                    |   +   | *** |      -       | **  |      -      | *** |
|              |                      | PDQ                     |   +   | *** |      +       |     |      +      | *** |
|              |                      | Soil C                  |   +   | *** |      -       |     |      -      | **  |
|              | Main effect only     | Elevation               |   +   | *** |              |     |             |     |
|              |                      | MAP                     |   +   | *** |              |     |             |     |
|              |                      | Surface T               |   +   | *** |              |     |             |     |
|              |                      | PC1                     |   +   | *** |              |     |             |     |
|              | Region only          | CEC                     |   -   |     |      -       | *** |             |     |
|              |                      | Clay                    |   +   |     |      -       | *** |             |     |
|              |                      | pH                      |   -   |     |      -       | *** |             |     |

Table: Table 2: ...

![Figure 1: Simple linear regressions of the common language effect size (_CLES_; ref) of (a--i) various forms of EH and (j) the first principal component of EH (PC1), where the _CLES_ is treated as the effect of GCFR relative to SWAFR values. Only significant (_P_ ≤ 0.05) fits are plotted, with the exception of the fit for CEC, which was plotted in light of its marginal significance (_P_ = 0.06). Grey bands denote 95% confidence intervals about the fitted lines. Across the five spatial scales, all _CLES_-values differed significantly from zero following two-sided $t$-tests (_P_ < 0.001). PC1 accounted for between 43.64 and 46.40% of the variation in EH values across the five spatial scales at which it was calculated.](figures/fig-1-CLES-EH-fits.pdf)

![Figure 2: (a) Scatter plot of mean QDS-scale richness ($\overline{S}$~QDS~) and turnover (_T_~QDS~) with contour lines denoting the _S_~HDS~ that would arise as their sum (i.e. increasing from lower-left to upper-right). Distributions of (a) HDS-scale species richness (_S_~HDS~) and (b) the turnover partition of that richness expressed as a proportion (_T_~QDS~ / _S_~HDS~). _CLES_-values inset are for comparisons where GCFR EH-values are greater than SWAFR EH-values; _P_-values inset are from Mann-Whitney _U_-tests. Not shown here, when comparing raw QDS-scale species richness values (_S_~QDS~), the results are as follows: _CLES_ = 0.60, _P_ < 0.001.](figures/fig-2-partition-richness_manual-edit.png)

![Figure 3: Fits of simple linear regressions of (a) _S_~HDS~ (_R_^2^ = 0.23) and (b) _S_~QDS~ (_R_^2^ = 0.15) against each respective scale's PC1-values. Grey bands denote 95% confidence intervals. When calculated at the QDS-scale, PC1 explained 39.86% of the variation in EH, while at the HDS-scale PC1 explained 41.55% of the variation in EH](figures/fig-3-PC1-model-fits.pdf)

![Figure 4: Slope estimates of the multiple linear regressions of (a) _S_~HDS~ (_R_^2^~adj~ = 0.49) and (b) _S_~QDS~ (_R_^2^~adj~ = 0.33) againt the various forms of EH. Each model was simplified, from a starting model with all predictors and their interactions with region, using reverse stepwise regression model selection based on _AIC_-scores in R. Points with error bars denote slope estimates and their 95% confidence intervals. Estimates illustrated in black were significant (_P_ < 0.05), while those in grey were not.](figures/fig-4-multivariate-model-terms.pdf)
