---
title    : "Analyses & results"
subtitle : "GCFR vs SWAFR manuscript"
author   : "Ruan van Mazijk"
date     : "`r Sys.Date()`"
output   : [pdf_document, word_document]
geometry : a4paper, margin=1in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo     = FALSE,
	fig.path = "figures/",
	message  = FALSE,
	warning  = FALSE
)
options(knitr.kable.NA = '')
```

# 1. Comparing environmental heterogeneity

```{r plot-PC1-of-EH, eval=FALSE}
# TODO: neaten this plot up for SI
heterogeneity_PCAs %>%
  map2(heterogeneity,
    ~ autoplot(.x, data = .y, colour = "region",
      alpha = 0.25,
      loadings       = TRUE, loadings.colour       = "black",
      loadings.label = TRUE, loadings.label.colour = "black",
      loadings.label.hjust = -0.25
    ) +
    ggtitle(unique(.y$scale)) +
    geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.5) +
    geom_vline(xintercept = 0, linetype = "dashed", alpha = 0.5)
  ) %>%
  {plot_grid(plotlist = .)}
```

# 2. Comparing species richness

```{r explore-collection-effort, eval=FALSE}
ggplot(data$QDS, aes(QDS_richness, n_collections, colour = region)) +
  geom_abline(intercept = 0, slope = 1) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
ggplot(data$HDS, aes(HDS_richness, n_collections, colour = region)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
ggplot(data$DS, aes(DS_richness, n_collections, colour = region)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()

ggplot(data$QDS) +
  aes(n_collections, n_collections/QDS_richness, colour = region) +
  geom_smooth(method = lm) +
  geom_point() +
  labs(
    x = "No. collections in QDS", 
    y = "No. collections per species in QDS"
  ) +
  scale_x_log10() +
  scale_y_log10()
ggplot(data$QDS) +
  aes(QDS_richness, n_collections*QDS_richness, colour = region) +
  geom_point()

ggplot(data$HDS) +
  aes(n_collections, HDS_richness, colour = region) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  lims(x = c(0, 2e4), y = c(0, 2e4))

size_of_choice <- function(n = 100) {
  d <- data.frame(x = 1:n)
  d$y <- choose(n, d$x)
  plot(y ~ x, d,type = "l")
}
size_of_choice()

1:nrow(data$HDS) %>%
  map_dfr(.id = "sample_size", ~sample_n(data$HDS, .x)) %>%
  group_by(region, sample_size) %>%
  summarise(HDS_richness = mean(HDS_richness)) %>%
  ungroup() %>%
  mutate(sample_size = as.numeric(as.character(sample_size))) %>%
  ggplot(aes(sample_size, HDS_richness, colour = region)) +
    geom_point()

ggplot(data$QDS) +
  aes(n_collections, QDS_richness/n_collections, colour = region) +
  geom_point() +
  labs(
    x = "No. collections in QDS", 
    y = "No. species per collection in QDS"
  ) +
  scale_x_log10()

ggplot(data$HDS) +
  aes(n_collections, HDS_richness/n_collections, colour = region) +
  geom_point() +
  labs(
    x = "No. collections in HDS", 
    y = "No. species per collection in HDS"
  ) +
  scale_x_log10()

ggplot(data$DS) +
  aes(n_collections, DS_richness/n_collections, colour = region) +
  geom_point() +
  labs(
    x = "No. collections in DS", 
    y = "No. species per collection in DS"
  ) +
  scale_x_log10()

ggplot(data$QDS, aes(QDS_richness/n_collections, fill = region)) +
  geom_histogram(position = "dodge")
ggplot(data$HDS, aes(HDS_richness/n_collections, fill = region)) +
  geom_histogram(position = "dodge")
ggplot(data$DS, aes(DS_richness/n_collections, fill = region)) +
  geom_histogram(position = "dodge")

data %$%
  HDS %>%
  mutate(QDS_turnover_std =
    ((HDS_richness/n_collections) - (mean_QDS_richness/n_collections)) #/
    #(HDS_richness/n_collections)
  ) %>%
  ggplot(aes(QDS_turnover_std, fill = region)) +
    geom_histogram(position = "dodge")

ggplot(data$QDS, aes(lon, lat, colour = n_collections)) +
  geom_point(size = 3) +
  facet_grid(~region, scales = "free_x") +
  scale_colour_viridis_c()
ggplot(data$HDS, aes(lon, lat, colour = n_collections)) +
  geom_point(size = 5) +
  facet_grid(~region, scales = "free_x") +
  scale_colour_viridis_c()
ggplot(data$DS, aes(lon, lat, colour = n_collections)) +
  geom_point(size = 10) +
  facet_grid(~region, scales = "free_x") +
  scale_colour_viridis_c()
```

# 3. Environmental heterogeneity as an explanation of species richness

## 3.1. Univariate models

```{r plot-PC1-models, eval=FALSE, fig.width=7, fig.height=3, fig.cap="..."}
PC1_explained_var <- heterogeneity_PCAs[2:4] %>%
  map(summary) %>%
  map("importance") %>%
  map(~.x[2, "PC1"]) %>%
  map(multiply_by, 100) %>%
  map(round, digits = 2)

data_for_PC1_plots <- 
  rbind(
    cbind(scale = "QDS", data %$%
      QDS %>%
      dplyr::select(region, QDS_richness, PC1) %>%
      rename(richness = QDS_richness)
    ),
    cbind(scale = "HDS", data %$%
      HDS %>%
      dplyr::select(region, HDS_richness, PC1) %>%
      rename(richness = HDS_richness)
    ),
    cbind(scale = "DS", data %$%
      DS %>%
      dplyr::select(region, DS_richness, PC1) %>%
      rename(richness = DS_richness)
    )
  ) %>%
  as_tibble() %>%
  mutate(scale = case_when(
    scale == "QDS" ~ bquote("(a)~QDS~~(italic(R)^2 == '0.08')"),
    scale == "HDS" ~ bquote("(b)~HDS~~(italic(R)^2 == '0.10')"),
    scale == "DS"  ~ bquote("(c)~DS~~(italic(R)^2 == '0.35')")
  ))
translucent_white <- rgb(1, 1, 1, 0.5)
ggplot(data_for_PC1_plots, aes(PC1, richness)) +
  geom_point(aes(fill = region), shape = 21, colour = "black") +
  geom_smooth(method = lm, colour = "black") +
  ylab(bquote(italic("S"))) +
  xlab(paste0(
    "PC1 (", PC1_explained_var$QDS, "%)                              ",
    "PC1 (", PC1_explained_var$HDS, "%)                              ",
    "PC1 (", PC1_explained_var$DS,  "%)"
  )) +
  scale_y_log10() +
  scale_fill_manual(name = "Region", values = c("black", translucent_white)) +
  facet_grid(~scale, scales = "free_x", labeller = label_parsed) +
  theme(
    legend.position   = c(0.9, 0.2), 
    legend.background = element_rect(fill = NA),
    axis.text.y       = element_text(angle = 90, hjust = 0.5),
    strip.text        = element_text(hjust = 0)
  )
```

## 3.2. Multivariate models

```{r more-maps, eval=FALSE}
ggplot(data$QDS, aes(lon, lat, colour = multivariate_residual)) +
  geom_point(size = 3) +
  facet_grid(~region, scales = "free_x") +
  scale_colour_viridis_c()
ggplot(data$HDS, aes(lon, lat, colour = multivariate_residual)) +
  geom_point(size = 5) +
  facet_grid(~region, scales = "free_x") +
  scale_colour_viridis_c()
ggplot(data$DS, aes(lon, lat, colour = multivariate_residual)) +
  geom_point(size = 10) +
  facet_grid(~region, scales = "free_x") +
  scale_colour_viridis_c()
```

```{r, eval=FALSE}
models_summary_for_plot %>%
  mutate(
    scale = c(0.25, 0.50, 1.00)[as.numeric(as.factor(response))],
    term_effect = paste(term, region)
  ) %>%
  ggplot() +
    aes(
      scale, estimate,
      fill = region, shape = region, group = term_effect
    ) +
    geom_hline(yintercept = 0, linetype = "dashed", colour = "grey75") +
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0) +
    geom_point() +
    labs(
      x = "Spatial scale",
      y = bquote("Effect"~~"("*italic("S")*")")
    ) +
    scale_fill_manual(values = c(NA, "black", "white")) +
    scale_shape_manual(values = c(4, 21, 21)) +
    scale_alpha_manual(values = c(1, 0.25)) +
    facet_wrap(~term, nrow = 2) +
    theme(
      axis.text.x  = element_text(angle = 90, hjust = 1, vjust = 0.5),
      axis.text.y  = element_text(angle = 90, hjust = 0.5),
      strip.text.x = element_text(angle =  0, hjust = 0)
    )
```

```{r, eval=FALSE}
data_all_scales <- data %$% rbind(
  QDS %>%
    rename(richness = QDS_richness) %>%
    add_column(scale = "QDS") %>%
    dplyr::select(scale, region, Elevation:pH, richness),
  HDS %>%
    rename(richness = HDS_richness) %>%
    add_column(scale = "HDS") %>%
    dplyr::select(scale, region, Elevation:pH, richness),
  DS %>%
    rename(richness = DS_richness) %>%
    add_column(scale = "DS") %>%
    dplyr::select(scale, region, Elevation:pH, richness)
)
full_formula <- predictor_names[predictor_names != "PC1"] %>%
  {c(., paste(., "* region * scale"))} %>%
  paste(collapse = " + ")

m_all_scales <- lm(glue("richness ~ {full_formula}"), data_all_scales)
m_all_scales %<>% step()
preds_w_interactions <- m_all_scales %$%
  coefficients %>%
  names() %>%
  magrittr::extract(str_which(., ":(regionSWAFR|scale.?DS)"))
reparameterisation <- preds_w_interactions %>%
  str_remove(":(regionSWAFR|scale.?DS)") %>%
  unique() %>%
  {glue("-{.}")} %>%
  paste(collapse = " ")
m_all_scales %<>% update(
  formula = glue(". ~ . {reparameterisation}"),
  data    = data_all_scales
)
summary(m_all_scales)
m_all_scales %>%
  tidy(conf.int = TRUE) %>%
  dplyr::select(-std.error, -statistic) %>%
  filter(term != "(Intercept)") %>%
  mutate(
    region = 
      case_when(
        str_detect(term, "regionSWAFR") ~ "SWAFR", 
        str_detect(term, "regionGCFR")  ~ "GCFR",
        TRUE                            ~ "Main effect only"
      ) %>%
      factor(levels = c("Main effect only", "GCFR", "SWAFR")),
    scale =
      case_when(
        str_detect(term, "scaleQDS") ~ "QDS", 
        str_detect(term, "scaleHDS") ~ "HDS",
        str_detect(term, "scaleDS")  ~ "DS"
      ) %>%
      factor(levels = c("Main effect only", "QDS", "HDS", "DS")),
    term = term %>%
      str_replace_all("_", " ") %>%
      str_remove_all("(scale|region)(.?DS|(SWA|GC)FR):"),
    sig = ifelse(p.value < 0.05, "< 0.05", "NS")
  ) %>%
  filter(term %in% var_names) %>%
  mutate(term = factor(term, levels = c(var_names, "regionSWAFR", "scaleQDS", "scaleHDS"))) %>%
  ggplot() +
    aes(
      term, estimate,
      colour = scale, fill = region, shape = region,
      alpha = sig
    ) +
    geom_hline(yintercept = 0, linetype = "dashed", colour = "grey75") +
    geom_errorbar(
      aes(ymin = conf.low, ymax = conf.high),
      position = position_dodge(width = 0.25),
      width = 0
    ) +
    geom_point(position = position_dodge(width = 0.25), size = 2) +
    labs(
      x = "Heterogeneity predictor",
      y = bquote(
        "Effect"~~
        "(log"["10"]*italic("S")*")"
      )
    ) +
    scale_fill_manual(values = c(NA, "black", "white")) +
    scale_shape_manual(values = c(4, 21, 21)) +
    scale_alpha_manual(values = c(1, 0.25)) +
    guides(
      fill = FALSE,
      shape = guide_legend(
        title = "Effect type",
        override.aes = list(fill = c(NA, "black", "white"))
      ),
      alpha = guide_legend(
        title = bquote(italic("P")["Effect"]),
        override.aes = list(alpha = c(1, 0.25), linetype = NA)
      )
    ) +
    theme(
      axis.text.x  = element_text(angle = 90, hjust = 1, vjust = 0.5),
      axis.text.y  = element_text(angle = 90, hjust = 0.5),
      strip.text.x = element_text(angle =  0, hjust = 0)
    )
```
