---
title: New richness-turnover models (+ fixed data!)
subtitle: Cape vs SWA publication
author: Ruan van Mazijk
date: '`r format(Sys.time(), "%F")`'
output: pdf_document
---

When I last left you two, the to-do list was as follows:

1. Investigate _mysterious_ axis numbering in Fig. 1.
2. Try modelling $HDS \ richness \sim \overline{QDS \ richness} + \overline{QDS \ turnover}$ etc. separately for each region
3. Try to score and/or partition HDS richness ($\gamma$, or a kind of regional/larger scale richness) into its mean QDS richness and turnover components ($\alpha$ and $\beta$)

# Misnumbered axes

Regarding item no. 1 on the to-do list, I discovered an unsettling reality. I had miscalculated mean QDS richness[^1]. Don't worry, though! I re-did it (Fig. 2,3) and although the pattern in the current equivalent of the figure above changed from curvilinear to just linear, it seems the turnover data was almost correct (I recalculated it---small changes). The relationships and conclusions we've been (trying) to draw are almost identical, so this hasn't set us back---I haven't missed a beat depsite this mistake.

[^1]: In detail, I was grouping QDS into HDS incorrectly, with what seems like a lag in the window function. Still not entirely sure what precisely went wrong. After generating these data again with `vegan` (which I had previously failed to do) and the QDS geocode system to **strictly** group QDS into HDS, I am more confident than ever that these data are correct.

# New models

## Defining the new models

Regarding to-do list item no. 2, I have fit the following models, separately for the Cape and SWA:

1. $HDS \ richness \sim \overline{QDS \ richness}$
2. $HDS \ richness \sim \overline{QDS \ richness} + \overline{QDS \ turnover}$
3. $HDS \ richness \sim \overline{QDS \ richness} * \overline{QDS \ turnover}$

And a null model ($\overline{HDS \ richness}$), too, for each region.

## Comparing model parameterisations nos. 0--3

I compared these models using likelihood ratio tests and $\Delta AIC$-scores.

What I find (Tables 1,2) is that there is support for there being an interaction between mean QDS richness and turnover in affecting HDS richness. Interestingly, the models with only additive effects (model parameterisation no. 2), is incredibly poorly supported.

I think, then, we should and can interpret the interaction-effects models (parameterisation no. 3), the summaries of the coefficients of which are in Table 3.

## Interpreting model parameterisation no. 3

If we imagine the HDS richness surface as a function of mean QDS richness and turnover, then Fig. 4 and 5 represent Fig. 2 with regression lines that are "slices" of the regressed HDS richness surface ("sliced" at the turnover values keyed).

From this we can see that increasing mean QDS turnover causes mean QDS richness to have a greater positive effect on HDS richness.

This makes sense to me, as it shows how QDS richness and turnover act synergistically to produce HDS richness.

What is nice to compare between Fig. 4 and 5 (Cape and SWA models, respectively), is that this synergy is strongest in SWA. I.e., Cape richness is more strongly determined by higher alpha richness.

This is complicated by how SWA has lower observed turnover values... 

But I shall leave that for a discussion with you two in person.

--Ruan
