---
title: The _expected_ dissimilarity of communitites of equal richness
subtitle: Cape vs SWA publication
author: Ruan van Mazijk
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width = 4, fig.height = 2
)
library(tidyverse)
library(viridis)
theme_set(theme_bw() + theme(
  panel.background = element_rect(fill = "white"),
  panel.border = element_rect(fill = NA, colour = "black")
))
```

Define the expected Jaccard similarity coefficient for two communities of richness $m$, drawn from a species pool of richness $n$

```{r def-exp-jacc}
exp_jacc_sim <- function(n, m) {
  j <- 0:(m - 1)
  ans <-
    (1 / choose(n, m)) *
    sum(
      ((m - j) / (m + j)) *
      choose(m, m - j) *
      choose(n - m, j)
    )
}
```

Calculate $E(J(A,B))$ for ranges of $n$ and $m$

```{r calc-exp-jacc}
data <- expand.grid(n = 1:100, m = 1:100)
data$exp_jacc_dist <- NA
for (i in 1:nrow(data)) {
  data$exp_jacc_dist[[i]] <- 1 - exp_jacc_sim(data$n[[i]], data$m[[i]])
}
```

```{r plot, echo=FALSE, fig.cap="Plot of $E(J(A,B))$ as a function of $m$ (without the $\\pm \\infty$s and NAs)"}
data %>%
  filter(exp_jacc_dist <= 1, exp_jacc_dist >= 0) %>%
  ggplot(aes(m, exp_jacc_dist, col = n, group = n)) +
    geom_line() +
    ylab("E(J(A,B))") +
    scale_color_viridis()
```
