---
title: Generating communities of desired $\beta$
subtitle: Cape vs SWA publication
author: Ruan van Mazijk
date: '`r Sys.Date()`'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.width = 4, fig.height = 2
)
library(tidyverse)
library(viridis)
theme_set(theme_bw() + theme(
  panel.background = element_rect(fill = "white"),
  panel.border = element_rect(fill = NA, colour = "black")
))
```

Generate pairs of communities that result in $J(A,B) \in [0, 1]$

```{r generate-communities}
data <- expand.grid(
  jacc_dist_ab = seq(0, 1, by = 0.1),
  richness_a = 1:11
)
data$richness_b <- data$richness_a
data$richness_ab <- NA
for (i in 1:nrow(data)) {
  data$richness_ab[[i]] <-
    data$richness_a[[i]] + (data$jacc_dist_ab[[i]] * data$richness_b[[i]])
}
```

```{r plot, echo=FALSE, fig.cap="Plot of the combined richess of communities $a$ and $b$ as a function of $J(A,B)$ and each community's richness (where richnness $a$ = richness $b$)"}
ggplot(data, aes(jacc_dist_ab, richness_a, fill = richness_ab)) +
  geom_tile() +
  labs(x = "J(A,B)", y = "Community richness") +
  scale_fill_viridis(name = "Richness A + B")
```
